### PR TITLE
Update packages version and ready for pnpm

### LINKED ISSUE #1189: Installation fails often with npm/pnpm because typescript-eslint🐛 and some others errors [Bug report]:
### Descrcibe the bug?

Some people as myself noted that sometimes, we can't install the application because an error happens with typescript-eslint because the module is missing but it's present in the package.son file.

No problem when the installation is done with Yarn nevertheless.

### Steps to reproduce the bug?

Clone the repository.
Install with pnpm
Start the application

We got this message
image

In the same way, we got problems with the process.env variables that are not found 

image

or some missing icons from react-icons.
image

### Expected behavior

Installation needs to be done with every package manager without errors.

### Desktop (Please provide your system information)

Device : Laptop Hp
Windows 11
browser : Vivaldi / Chrome (@latest)  

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Angra974**
# Description

Using pnpm to install the application is beneficial if you install often packages or if you have a slow network with other benefits. pnpm store the packages in a folder and use them when needed instead of download them again.

Nevertheless, we have a warning with the current installation regarding eslint :

Capture d’écran du 2023-10-13 22-32-48

We need to adjust the dependencies so we can take off this warning.
Before, some people was unable to install with pnpm too because of this problem with eslint.

Fixes #1189

## Type of change

Updated the dependencies and their peer dependencies to get no more warning

Only package.json and eslintrc.js was changed by my work.
The other files result in the format and lint of the file with the new version of the modules.

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Lint after install the current reactplay.
Update the dependencies and the related peer dependencies 
Lint after update.
Add configuration in .eslintrc.js to get warnings instead of errors for unused vars.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
=> the basic lint command.

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
Capture d’écran du 2023-10-13 23-38-34

[video](https://streamable.com/su1xt7)
Capture d’écran du 2023-10-14 11-25-25
Capture d’écran du 2023-10-14 11-27-07
Capture d’écran du 2023-10-14 11-28-13

Remark: Husky commit use Yarn, so ^^'

Notice :
i've updated the .gitignore file to : 
   - ignore a test created for cypress that will be placed in cypress/e2e, created by create-react-play  if [#PR46](https://github.com/reactplay/create-react-play/pull/46)  is validated by no impact on actual app
   - ignore a file index.json file in the plays folder, created by create-react-play if PR is validated by no impact on actual app ( will be done in some time ).

### CODE REVIEW

**Comment by priyankarpal** [comment]
We should upgrade all the dependencies since a few of them have become deprecated. @Angra974

**Comment by Angra974** [comment]
> We should upgrade all the dependencies since a few of them have become deprecated. @Angra974

Updating all the dependencies means to modify codes inside the application ( change between swiper 9 to 10 ). 
Some components needs to be lightly modified.
Some dependencies will not be changed because the plays associated with them won't work ( code-editor for exemple ). 
I won't be able to test them with Yarn.
Only pnpm and npm as it is use with the workflow here.

**Comment by Angra974** [comment]
This one is ready.
Deploy is ok.
Less modifications than expected as some are not update to the last version. 
Will come later as they needs update in code and will take more time to be validated.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Review by supminn — APPROVED** [review]

**Comment by priyankarpal** [comment]
so now we need to change the docs according to `pnpm` such as (`pnpm i`, `pnpm dev`)

**Pull request merged**
