### PR TITLE
[#2PlaysAMonth]: Pixy - Pixel Art Creator

### LINKED ISSUE #965: [#2PlaysAMonth]: Pixy
### What's the Play about?

Unleash your creative mind by creating pixel art. User will be able to select color from the color palette and generate any pixel art.

### What ReactJS concept will be used to create this play?

Hooks, Components

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by raibove**
# Description

This tool allows users to create Pixel art by placing colored squares on a grid and saving them as a jpg image.

Fixes #965  (issue)

# How Has This Been Tested?

Manually tested.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

pixy_react_play

### CODE REVIEW

**Review by koustov — CHANGES_REQUESTED** [review]
1. Use `cover.png` instead of `cover.jpg`
2. Please record a demo video on stackstream
Rest looks good

**Comment by atapas** [comment]
> Visit Preview

Hey @raibove this is so close to done. I want to merge it. Please take care asap/

**Comment by raibove** [comment]
> > Visit Preview
> 
> Hey @raibove this is so close to done. I want to merge it. Please take care asap/

I have updated the cover from jpg to png, but for video I have already added lin in readme, do I need to add it somewhere else too?

**Comment by atapas** [comment]
> > > Visit Preview
> > 
> > 
> > Hey @raibove this is so close to done. I want to merge it. Please take care asap/
> 
> I have updated the cover from jpg to png, but for video I have already added lin in readme, do I need to add it somewhere else too?

You just need to edit your play from localhost(click on the edit button in the play header) and add the link.

**Comment by raibove** [comment]
> > > > Visit Preview
> > > 
> > > 
> > > Hey @raibove this is so close to done. I want to merge it. Please take care asap/
> > 
> > 
> > I have updated the cover from jpg to png, but for video I have already added lin in readme, do I need to add it somewhere else too?
> 
> You just need to edit your play from localhost(click on the edit button in the play header) and add the link.

I have edited the play and added video link

**Comment by raibove** [comment]
@atapas Can you check if any changes are required and merge this PR

**Review by atapas — APPROVED** [review]

**Pull request merged**
