### PR TITLE
fix: overlapping on navbar in mobile device

### LINKED ISSUE #602: 🐛 [Bug report]:
**Describe the bug**
Hacker-play Text overlapping on navbar in mobile device 

**To Reproduce**
1. Open reactplay.io in mobile or similar resolution mode
2. Click on  hamburger menu
3. you can notice the text overlapping 

**Expected behavior**
Text shouldn't be overlapped on navbar

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by dharmiknotop**
# Description

You guys added a z-index of 10 to the body content and z-index of 1 to the navbar which makes the body content rise above the navbar making ui overlap solved this by making the body-content's z-index to one.

Fixes  #602

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manually saw that does it affect the desktop ui, no it doens't affect that does it solve the overlapping for mobile screen? yes.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

image

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@dharmiknotop , Can you attach the screenshot?

**Comment by dharmiknotop** [comment]
@Sachin-chaurasiya updated it

**Comment by Sachin-chaurasiya** [comment]
@dharmiknotop , As we are changing the z-index of the app body, can you test it thoroughly?

**Comment by atapas** [comment]
@dharmiknotop This issue is already been fixed and merged. 

@Sachin-chaurasiya Do you still see it on the updated code?

**Comment by Sachin-chaurasiya** [comment]
> @dharmiknotop This issue is already been fixed and merged. 
> 
> @Sachin-chaurasiya Do you still see it on the updated code?

@atapas , Just checked on my phone and it's working fine.

**Comment by atapas** [comment]
> > @dharmiknotop This issue is already been fixed and merged.
> > @Sachin-chaurasiya Do you still see it on the updated code?
> 
> @atapas , Just checked on my phone and it's working fine.

Ok thanks for confirming. So @dharmiknotop, I think you should focus on other issues.

**Comment by dharmiknotop** [comment]
@atapas okie

**Comment by atapas** [comment]
Closing the PR.

**Pull request closed without merging**
