### PR TITLE
feat: support to select  multiple filters

### LINKED ISSUE #192: ✨ [Feature request]: Better way of searching tags and creator in folter modal
**Is your feature request related to a problem? Please describe.**
It's a little frustrating to find a tag or use from the list in the filter modal. The frustration part comes from the fact that the list is growing and there is nothing to sort/filter them

Loosely related to #14

**Describe the solution you'd like**
- A filterable typeahead for creator and tags
- Tags and creator dropdown should be sorted
- Avoid duplicate in tags

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by supminn**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
Previously, only a combination of 1 level, 1 creator, and 1 Tag was available at a time. 
I have implemented the option to select multiple values of each combination. (Screenshot attached below)

Fixes # (issue)
- #24 
- #472 
- #696
- Partially fixes #192. Filter options are displayed in a sorted manner.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots
image
image

### CODE REVIEW

**Comment by atapas** [comment]
Hey @koustov Please take a look.

**Comment by koustov** [comment]
> Hey @koustov Please take a look.

@supminn do you still have the issue? I have already published the package as I mentioned in (this pr)[https://github.com/koustov/json-graphql-parser/pull/4]

**Comment by supminn** [comment]
> > Hey @koustov Please take a look.
> 
> @supminn do you still have the issue? I have already published the package as I mentioned in [this pr](https://github.com/koustov/json-graphql-parser/pull/4)

Hi @koustov 
I didn't get a chance to work on this for the last 2-3 days. I'll work on it and update you by tomorrow EOD.

**Comment by supminn** [comment]
Hi @koustov 
I am facing a few blockers while working with the latest changes. I have mentioned the details on discord.
Could you please let me know a suitable time to connect in this regard?

**Comment by koustov** [comment]
@supminn is it ready to be reviewed?

**Comment by supminn** [comment]
> @supminn is it ready to be reviewed?

Yes @koustov, could you please review the changes.
I had dropped a message on #pr_review in discord.

**Review by koustov — APPROVED** [review]
Looks good to me

A couple of notes
1. Cypress is failing with some timeout. Until that one is passed, I will not be able to merge
2. @supminn It would be nice if we give a search/filter box for creator dropdown. Can you create an issue?

**Pull request merged**
