### PR TITLE
Issue 1044 play filter by url params

### LINKED ISSUE #1044: ✨ [Feature request]: Play filter should be driven from URL
### Is your feature request related to a problem? Please describe.

For a persistent and bookmark-able play list, application should drive the filter through URL not in app

### Describe the solution you'd like.

Any update to filter should add a query string to URL params 

### Describe alternatives you've considered.

NA

### Screenshot / Screenshare

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by koustov**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1044 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
I found a few issues so far and posting here:

- Is the text search searches on play name alone? Or description too?

I search with a text that is similar to a play name

image

It doesn't result me the play

image

**Comment by atapas** [comment]
Filter by Tag #2PlaysAMonth doesn't work!

image

**Comment by atapas** [comment]
Filtered by a user(Tapas Adhikary).. The filter worked.

image

But when I click on the filter icon again, the filter popup doesn't appear(unless I clear the filter manually)

**Comment by koustov** [comment]
I tested all of them locally, was working. Will check and fix.

**Comment by koustov** [comment]
@atapas  its up for next round of testing

**Review by atapas — APPROVED** [review]

**Pull request merged**
