### PR TITLE
Add Readme.md file for all the missing Plays!

### PR DESCRIPTION
**Pull request by atapas**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Add Readme.md file for all the missing Plays!

Fixes # 248

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@murtuzaalisurti I am done with all the readme changes for the missing ones. For your play, could you please add the details and let me know?

**Comment by murtuzaalisurti** [comment]
> @murtuzaalisurti I am done with all the readme changes for the missing ones. For your play, could you please add the details and let me know?

sure, it will be done by today!

**Comment by murtuzaalisurti** [comment]
> @murtuzaalisurti I am done with all the readme changes for the missing ones. For your play, could you please add the details and let me know?

updated the README of the play 'counter'! you can merge now!

**Review by murtuzaalisurti — APPROVED** [review]
LGTM

**Pull request merged**
