### PR TITLE
Fix Edit event modal pop-up on save click

### LINKED ISSUE #584: 🐛 [Bug report]: On Clicking "Save" the edit event modal not closing.
**Describe the bug**
If you try to edit an event and click on `Save` button the previous edit modal is showing. In my understanding it should not be like that. Just like `Deleting` an event, once you click on `Save` button the whole modal should be closed. 

**To Reproduce**
1. Go to '[Calender App](https://reactplay.io/plays/vincentbcp/calendar)'
2. Click on any "Event" and then Edit "Button"
3. Once you are done with `Edit` and click on the `Save` button.

**Expected behavior**
Once you click on the `Save` button after editing the event, the whole modal should be closed.

**Screenshots**

https://user-images.githubusercontent.com/55223302/193423528-19ab439a-ea6f-4556-be66-b15ef1ca55fe.mov

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : chrome, firefox, safari

**Smartphone (please complete the following information):**
 - Device: redmi K20 pro
 - OS: android
 - Browser: chrome

**Additional context**
If the flow should be like that only, then it's okay. If not, I am happy to fix it.

### PR DESCRIPTION
**Pull request by muzaffar640**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
I have added `onCancel()` if the event is true. So when you edit an event and click on `Save`, it will close the whole edit event modal.

Fixes #584

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

1. Clicked on an "Event" on the calendar and then the `Edit` button
2. Once done with Edit and click on the Save button.
3. The whole modal is getting close.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshare

https://user-images.githubusercontent.com/55223302/193459824-93a5e10f-7b1f-47a0-bcf5-9d5dbd03bbb2.mov

### CODE REVIEW

**Comment by muzaffar640** [comment]
Review Ready

**Comment by Sachin-chaurasiya** [comment]
@muzaffar640 , Can you attach some screen recordings?

**Review by Sachin-chaurasiya — DISMISSED** [review]

**Comment by muzaffar640** [comment]
> @muzaffar640 , Can you attach some screen recordings?

Thank you for the review @Sachin-chaurasiya , I have updated the comment with a screen recording.

**Comment by muzaffar640** [comment]
Rebased and Review Ready

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by koustov — APPROVED** [review]
lgtm

**Pull request merged**
