### PR TITLE
[#2PlaysAMonth]: Hex to tailwind CSS Converter

### LINKED ISSUE #963: [#2PlaysAMonth]: Css(Hex) color to nearest Tailwind color conver
### What's the Play about?

This will convert Hex color to nearest tailwind color name if it is exists in default tailwind css color palet, or show you alternate color which you can chose from and tally to your input css hex color.

### What ReactJS concept will be used to create this play?

Components, hooks 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by debjit**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

Ticket Link: [issue#963](https://github.com/reactplay/react-play/issues/963)
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #963 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

Screen Shot 2023-02-23 at 12 10 45 AM

### CODE REVIEW

**Comment by atapas** [comment]
> Hey @debjit
> 
> A bunch of lint errors, please fix
> 
> image

@debjit any update?

**Comment by koustov** [comment]
I see one more issue
image

**Comment by debjit** [comment]
I will sure update tonight. Thank you for the reminder.

**Comment by koustov** [comment]
Just taking SC from discord for tracking purposes
image

**Comment by atapas** [comment]
@debjit is it done?

**Comment by debjit** [comment]
Hello @atapas I have updated please try to share what is the error msg. Thanks.

**Pull request closed without merging**
