### PR TITLE
fix:button text in center (#1107) #1110

### PR DESCRIPTION
**Pull request by mohammedkharoda**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Change the button text that align in the center and the issues is being address and fixes no depenices require just fixing the css 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Steps to reproduce the bug?
- On Smaller screens:

## Go to reactplay.io
- On Bigger Screens:

## Go to reactplay.io
- Open console
- Click on Device Toggle button

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x]  Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

image

### CODE REVIEW

**Comment by atapas** [comment]
@mohammedkharoda Which issue are you working on? What's the issue number?

**Comment by atapas** [comment]
Thanks @mohammedkharoda 

Have you checked this is prod? I see the button texts are already aligned center. Could you please confirm if that's the case?

image

**Comment by mohammedkharoda** [comment]
@atapas It was not aligned in mobile responsive so I fix that and I have check it is working as expected after modification

**Comment by atapas** [comment]
> @atapas It was not aligned in mobile responsive so I fix that and I have check it is working as expected after modification

Got it, Thanks!

**Comment by mohammedkharoda** [comment]
@atapas The issues is slove so can you merge it 😁😁

**Review by atapas — APPROVED** [review]

**Pull request merged**
