### PR TITLE
Update Contribute.md

### LINKED ISSUE #1108: ✨ [Feature request]: Add commit message guideline to contribute.md
### Is your feature request related to a problem? Please describe.

As I saw in the repository your commit messages didn't follow a guideline it will be better to have commit message guidelines and write some rules for that to have better commit messages because a good commit message is a good documentation for your project. 

### Describe the solution you'd like.

Add some commit message guidelines to your `contribute.md`. 

### Describe alternatives you've considered.

Nothing

### Screenshot / Screenshare

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AlirezaEbrahimkhani**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Update contribute.md and add links to specific parts of the doc and add commit message format rules

Fixes #1108

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
@AlirezaEbrahimkhani Can we have the issue number?

**Comment by AlirezaEbrahimkhani** [comment]
> @AlirezaEbrahimkhani Can we have the issue number?

There is no issue to link to this PR I just want to improve it.
As I saw in the big open-source repositories in GitHub having a commit message format is necessary because it is good documentation for your code on its own

**Comment by atapas** [comment]
> > @AlirezaEbrahimkhani Can we have the issue number?
> 
> There is no issue to link to this PR I just want to improve it. As I saw in the big open-source repositories in GitHub having a commit message format is necessary because it is good documentation for your code on its own

We must need an issue number to merge the work. Can you please create an issue with all details and get me that?

**Comment by atapas** [comment]
@AlirezaEbrahimkhani Please let me know the issue number. Otherwise we will not know why these changes are made.

**Comment by AlirezaEbrahimkhani** [comment]
> @AlirezaEbrahimkhani Please let me know the issue number. Otherwise we will not know why these changes are made.

@atapas 
All Done!

**Review by koustov — APPROVED** [review]
lgtm

**Comment by AlirezaEbrahimkhani** [comment]
@atapas 
Would you please review this PR again?

**Comment by atapas** [comment]
> @atapas 
> 
> Would you please review this PR again?

Will do tomorrow

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
Thanks @AlirezaEbrahimkhani for enhancing it. Great work!

**Pull request merged**
