### PR TITLE
[Bug Fix]: layout shift fix for #1105

### PR DESCRIPTION
**Pull request by Roshan-Horo**
# Description

This PR is a fix for Issue#1105 Layout shift

# Root Cause

The root cause of the issue that I find is that className (app-header-home -> contains position: fixed property) of a Header is applied after dynamic checking of a "showHideBits.setHeaderStyle", and also from ACTIVITIES_ON variable from .env file. That cause a jitter/layout shift in the screen.

# Fixes # (issue)

The easiest solution that I could find is use the className(app-header-home) before. so, it don't have to check dynamically.

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested using profiling.

# Screenshots or example output

## Before and After Issue Results ( lower the video playback speed on 0.25 and you can see the layout shift )

https://user-images.githubusercontent.com/35597955/231448904-50068702-b7ef-492d-85ef-832d475adec3.mp4

## Profiling After Issue got fixed.

https://user-images.githubusercontent.com/35597955/231448052-e1f9ab8c-3b31-494f-8f6d-5761a78e9038.mp4

## Profiling With Activites on

https://user-images.githubusercontent.com/35597955/231448243-1bd3661b-8009-4fea-80bd-823e1e9a606e.mp4

### CODE REVIEW

**Comment by Roshan-Horo** [comment]
Hi @atapas , why Cypress test fail? and how to fix it?

**Comment by atapas** [comment]
@Roshan-Horo Can you explain this fix please? Also confirm it was tested with the env variable value made true?

**Comment by Roshan-Horo** [comment]
Hi @atapas , I checked with other routes ( /leaderboard, /ideas ) and it's affect these routes with layout bug. So, this is **NOT** the correct way for fixing the issue #1105 . 

Root Cause : Main Issue here is HeaderStyle is depends on the route, and is dynamically checking the pathname and assign different object ( containing showBrowse, showSearch, setHeaderStyle ) to  showHideBits through "useEffect".

Ways to fix this :
- use "useLayoutEffect" instead of "useEffect" : this solves the issue but cost us **performance**, so I don't recommend it.

- "HeaderStyle" and "Header Items" is very dynamic ( depends on the route ) means for the '/' route : showBrowse: true, 
  showSearch: false and for other routes these values are different, you get the point.
  So, Instead of single Header Component in the main layout page, Create different Header for each page inside Page component.

That's my overall view on how we can fix the issue, let me know what you think.
Thanks,

**Comment by Roshan-Horo** [comment]
hi @atapas , @Sachin-chaurasiya , 

I created a dynamic header component, which can be used for creating different Headers based on different routes.

## Screenshot

With No Activites ( .env variable REACT_APP_ACTIVITIES_ON=false )

https://user-images.githubusercontent.com/35597955/233822503-0a016bde-cd3b-485b-9029-766f992de62b.mp4

With Activities ON ( .env variable REACT_APP_ACTIVITIES_ON=true )

https://user-images.githubusercontent.com/35597955/233822531-67678cc4-22ae-48b8-ae17-5799589e30d1.mp4

## Testing Manual

cypress:open
Screenshot (288)

## Some of line that are not changed but it includes because of **linting**.

Please check and review.

Thanks

**Comment by Sachin-chaurasiya** [comment]
> hi @atapas , @Sachin-chaurasiya ,
> 
> I created a dynamic header component, which can be used for creating different Headers based on different routes.
> 
> ## Screenshot
> With No Activites ( .env variable REACT_APP_ACTIVITIES_ON=false )
> 
>  after_change_na.mp4 
> With Activities ON ( .env variable REACT_APP_ACTIVITIES_ON=true )
> 
>  before_change_na.mp4 
> ## Testing Manual
> cypress:open Screenshot (288)
> 
> ## Some of line that are not changed but it includes because of **linting**.
> Please check and review.
> 
> Thanks

@Roshan-Horo , Can we create a separate ticket for the dynamic header and include that changes in a different PR?

**Pull request closed without merging**
