### PR TITLE
Budget app added

### LINKED ISSUE #367: [Add a Play]:  Budget App
## What's the Play about?
I would like to add a Budget app with which the user can plan their expense and categorize them really well. 

Live site: https://budget-app-adit0507.netlify.app/

## What ReactJS concept will be used to create this play?
Custom Hooks, Prop Drilling, Local Storage

## Are you willing to take it up for implementation?
Yes, I'm willing to build it.

I took reference from https://www.youtube.com/watch?v=yz8x71BiGXg to make this project.

### PR DESCRIPTION
**Pull request by Adit0507**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #367 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@Adit0507 I get a blank screen when go to the play using the preview link. Please have a look. Once fixed, I can start review.

**Comment by koustov** [comment]
> @Adit0507 I get a blank screen when go to the play using the preview link. Please have a look. Once fixed, I can start review.

+1 
image

**Comment by Adit0507** [comment]
@atapas @koustov  I'm not able to figure out the bug. I tried several things but it wasnt working out

**Comment by atapas** [comment]
@Adit0507 What's up with this one?

**Comment by Adit0507** [comment]
Sir I havent been able to figure out the bug with this one

**Comment by atapas** [comment]
> Sir I havent been able to figure out the bug with this one

You should leverage the need help channel in discord to get help. It's a great app idea, I'm sure someone from ReactPlay community can help you to close it.

**Comment by Adit0507** [comment]
> > Sir I havent been able to figure out the bug with this one
> 
> You should leverage the need help channel in discord to get help. It's a great app idea, I'm sure someone from ReactPlay community can help you to close it.

Yes sir

**Comment by atapas** [comment]
Hi @Adit0507 

A reminder to get back on this play. This PR may be closed due to a lack of activities soon. Please let us know if you need any help.

Looking forward to getting the play in!

**Comment by Adit0507** [comment]
> Hi @Adit0507
> 
> A reminder to get back on this play. This PR may be closed due to a lack of activities soon. Please let us know if you need any help.
> 
> Looking forward to getting the play in!

Sir I guess I"'ll have make a new PR for this.
Can I close this ?

**Comment by atapas** [comment]
> > Hi @Adit0507
> > A reminder to get back on this play. This PR may be closed due to a lack of activities soon. Please let us know if you need any help.
> > Looking forward to getting the play in!
> 
> Sir I guess I"'ll have make a new PR for this. Can I close this ?

Sure, go for it.

**Pull request closed without merging**
