### PR TITLE
loading string removed

### LINKED ISSUE #1064: 🐛 [Bug report]: there is a "loading..." string that gets visible sometimes
### Descrcibe the bug?

On the reactplay.io/plays page, there is a "loading..." string that gets visible sometimes after navigating between reactplay.io/ and reactplay.io/plays pages a few times.

### Steps to reproduce the bug?

1. Go to reactplay.io
2. Navigate a few times between the root and /plays page
3. Note the "loading..." under the header

### Expected behavior

The "loading..." string should not be shown and the top banner should have been visible

### Desktop (Please provide your system information)

OS: Windows 11
Browser: Chrome 
Version: 111.0.5563.64

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

Recording 2023-03-21 075328

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yeshwantthota**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1064 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings

- [x] New and existing unit tests pass locally with my changes

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
@yeshwantthota 

Fix the lint errors

image

**Comment by atapas** [comment]
@yeshwantthota Any update? We want to merge this.

**Comment by yeshwantthota** [comment]
> @yeshwantthota Any update? We want to merge this.

@atapas working on it

**Comment by atapas** [comment]
> > @yeshwantthota Any update? We want to merge this.
> 
> @atapas working on it

Let me know if you need help.

**Comment by yeshwantthota** [comment]
> > > @yeshwantthota Any update? We want to merge this.
> > 
> > 
> > @atapas working on it
> 
> Let me know if you need help.

yes , pls , I am trying to clear the lint errors by running command npm run lint, but its saying eslint is not found, I even tried to download and use it but its showing same thing

**Review by Mohitb07 — COMMENTED** [review]
@yeshwantthota One suggestion I have is to simplify the conditional rendering in the JSX. Instead of using the ternary operator, we could utilize the truthy/falsy value of the loading variable and directly return <Loader /> using an early return within the render phase itself. It could be written like this: 

```
if (loading) return <Loader />
```

**Comment by koustov** [comment]
Please resolve conflict

**Comment by Mohitb07** [comment]
I have addressed the banner loading state issue and submitted a pull request with a proposed solution. You can find the details of my changes in pull request #1136. Please feel free to review and provide your feedback. Thank you.

**Pull request closed without merging**
