### PR TITLE
Update Pull Request template

### PR DESCRIPTION
**Pull request by muzaffar640**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Added Screebshot or example output block to Pull Request Template

Fixes # [599](https://github.com/reactplay/react-play/issues/599)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Checked the output on VS Code using `command+shift+v`

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
Screenshot 2022-10-06 at 12 46 27 AM

### CODE REVIEW

**Comment by muzaffar640** [comment]
Review Ready

**Review by atapas — COMMENTED** [review]
@muzaffar640 This is good but I am thinking, can we go yml way so that it becomes more like form filling for the contributors? Are you aware of that template creation?

**Comment by atapas** [comment]
> > @muzaffar640 This is good but I am thinking, can we go yml way so that it becomes more like form filling for the contributors? Are you aware of that template creation?
> 
> No @atapas, I'm not aware of that. Can share some references, please?

Like this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

**Comment by muzaffar640** [comment]
@atapas I am playing around with it. From the documentation, I'm able to create various issue templates in yml way. And as you said it is looking really good 😁 . But for PR template, I have tried various methods to render the yml file but could not able to succeed. And didn't find any valid documentation also. Can you please help me with this one? Here is my test [repo](https://github.com/muzaffar640/mini-band/issues/4)

I want to update the issue template also if suggest. Please have a look at this. 

https://user-images.githubusercontent.com/55223302/194704866-1a246468-5b96-4dd9-8afc-ab9e3e69984b.mov

**Comment by atapas** [comment]
> @atapas I am playing around with it. From the documentation, I'm able to create various issue templates in yml way. And as you said it is looking really good 😁 . But for PR template, I have tried various methods to render the yml file but could not able to succeed. And didn't find any valid documentation also. Can you please help me with this one? Here is my test [repo](https://github.com/muzaffar640/mini-band/issues/4)
> 
> I want to update the issue template also if suggest. Please have a look at this.
> 
>  Screen.Recording.2022-10-08.at.1.27.13.PM.mov

It seems this support is for the issue alone. I also tried the PR template but not successful. Let us then do these.

- Will go ahead with your suggested changes for PR template you made originally.
- Change the issue templates.

We will continue the PR template using YAML in a separate issue. Does it sound good?

**Comment by muzaffar640** [comment]
> > @atapas I am playing around with it. From the documentation, I'm able to create various issue templates in yml way. And as you said it is looking really good 😁 . But for PR template, I have tried various methods to render the yml file but could not able to succeed. And didn't find any valid documentation also. Can you please help me with this one? Here is my test [repo](https://github.com/muzaffar640/mini-band/issues/4)
> > I want to update the issue template also if suggest. Please have a look at this.
> > Screen.Recording.2022-10-08.at.1.27.13.PM.mov
> 
> It seems this support is for the issue alone. I also tried the PR template but not successful. Let us then do these.
> 
> * Will go ahead with your suggested changes for PR template you made originally.
> * Change the issue templates.
> 
> We will continue the PR template using YAML in a separate issue. Does it sound good?

That will be better. I will create a new issue and PR for `Create Issue Template` with yml then. Thanks for the confirmation.

**Review by atapas — APPROVED** [review]

**Pull request merged**
