### PR TITLE
Updated the z-index of NavBar in order to always be on top

### LINKED ISSUE #593: 🐛 [Bug report]: Overflow content with NavBar while scrolling
The Content of the page overflows the content of NavBar while scrolling. 

image
You can see the hero title, as well as the hero image, overlap the content of the navbar.

This is generally caused by the z-index difference between the two.

We can resolve this by setting enough z-index differences between them.

### PR DESCRIPTION
**Pull request by arpitghura**
# Description

Actually, the bug is there which causes the content of the website to be overflow with NavBar, this generally caused by giving a low z-index value to the navbar. 
I have increased the value of the `z-index` from `10` to `99`, which is higher than all other website components, which means scrolling all other content will be scrolled below the navbar.

Fixes #593 

## Type of change
- Bug fix

# How Has This Been Tested?
I have tested this on my computer and it's working fine.

After fixing the bug:
image

# Checklist:

- [✔] I have performed a self-review of my own code
- [✔] My changes generate no new warnings
- [✔] I have added tests that prove my fix is effective or that my feature works
- [✔] New and existing unit tests pass locally with my changes
- [✔] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpitghura** [comment]
@Sachin-chaurasiya please allow vercel to deploy this PR.

**Comment by iamkelv** [comment]
Can you assign this issue for me? I'll like to work on it

**Comment by Sachin-chaurasiya** [comment]
> Can you assign this issue for me? I'll like to work on it

@iamkelv , Welcome to the community, @arpitghura is already working on this issue.
You can explore the more issues https://github.com/reactplay/react-play/issues.

**Comment by arpitghura** [comment]
The website at this pull request is live on Vercel, @Sachin-chaurasiya @ishrarg @atapas check this out 

[react-play-arpitghura.vercel.app](react-play-arpitghura.vercel.app) 
[react-play-dun.vercel.app](react-play-dun.vercel.app)
[react-play-git-main-arpitghura.vercel.app](react-play-git-main-arpitghura.vercel.app)

**Comment by arpitghura** [comment]
@atapas @koustov kindly review the PR and merge it.

**Comment by koustov** [comment]
Hello @arpitghura , I couldn't replicate the issue on reactplay.io. 
image

Can you give me a little more detailed replication step? Or has it been fixed with some other PR?

**Comment by arpitghura** [comment]
Hey, @koustov I am able to recreate the issue. The issue can be easily seen on the desktop version of the reactplay website. 

If you are viewing the website on a smartphone, you might be unable to recreate the issue. Kindly, check the desktop version of the website.

**Comment by koustov** [comment]
> Hey, @koustov I am able to recreate the issue. The issue can be easily seen on the desktop version of the reactplay website.
> 
> If you are viewing the website on a smartphone, you might be unable to recreate the issue. Kindly, check the desktop version of the website.

I am also running it from desktop (with chrome Version 106.0.5249.103), you can notice it on the screen capture. Can you re-create the issue on `reactplay.io` and paste the screen capture here?

**Comment by arpitghura** [comment]
> > Hey, @koustov I am able to recreate the issue. The issue can be easily seen on the desktop version of the reactplay website.
> > If you are viewing the website on a smartphone, you might be unable to recreate the issue. Kindly, check the desktop version of the website.
> 
> I am also running it from desktop (with chrome Version 106.0.5249.103), you can notice it on the screen capture. Can you re-create the issue on `reactplay.io` and paste the screen capture here?

I have seen that the issue is now fixed with some other pull requests. Previously the website is cached in the browser so it was showing the issue, but I now the browser is loading the updated source code of the repo.

**Comment by koustov** [comment]
> > > Hey, @koustov I am able to recreate the issue. The issue can be easily seen on the desktop version of the reactplay website.
> > > If you are viewing the website on a smartphone, you might be unable to recreate the issue. Kindly, check the desktop version of the website.
> > 
> > 
> > I am also running it from desktop (with chrome Version 106.0.5249.103), you can notice it on the screen capture. Can you re-create the issue on `reactplay.io` and paste the screen capture here?
> 
> I have seen that the issue is now fixed with some other pull requests. Previously the website is cached in the browser so it was showing the issue, but I now the browser is loading the updated source code of the repo.

Great, then lets close this PR and the issue.

**Comment by arpitghura** [comment]
Ya sure

**Pull request closed without merging**
