### PR TITLE
feature: configured ESLint/Prettier/Husky setup

### LINKED ISSUE #263: ✨ [Feature request]: Configure ESLint and Prettier
**Is your feature request related to a problem? Please describe.**
It will be nice to have standardized rules for coding.

**Describe the solution you'd like**
We can configure **ESLint** and **Prettier** in our project. Then if we set it up with Husky pre-push hook, the code will already be formatted and *prettified* before `git push` command is executed.

**Describe alternatives you've considered**
- Ignoring code formatting. 
- Manually reading/reviewing every code for better formating.

**Additional context**
I am happy to work on this issue.

### PR DESCRIPTION
**Pull request by joshi-kaushal**
# Description

Fixes #263 
I previously raised a similar PR #332, but this is the latest and better version of the issue.

This PR integrates Husky, Prettier, and ESLint with the repository. This will test **staged files** against the config before every commit.  
The existing files are yet to be fixed. I believe in creating a different branch and collaboratively resolving those errors/warnings for doing it. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by koustov** [comment]
I see this build time error 
image

**Comment by koustov** [comment]
Hey @joshi-kaushal i would like to get this PR in. A long-time one. Could you please resolve the conflict and fix the build error? Then it will be ready for merge.

**Comment by joshi-kaushal** [comment]
Hi @koustov 

I can not see the preview or error log for this build. Where can I see those?

**Comment by joshi-kaushal** [comment]
@Sachin-chaurasiya here

**Comment by atapas** [comment]
> * kaushal)

Nice! Can we put dates also on these tasks by when we can tentatively complete them?

**Pull request merged**
