### PR TITLE
[#2PlaysAMonth]: Expense tracker

### LINKED ISSUE #909: [#2PlaysAMonth]: Expense Tracker
### What's the Play about?

Build a play for tracking expenses. Add, remove, edit expenses, categorize them

### What ReactJS concept will be used to create this play?

Hooks, Typescript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by senali-d**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Expense Tracker

Build a play for tracking expenses. Add, remove, edit expenses.

Fixes #909 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Test locally.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by atapas** [comment]
@senali-d can you please associate the issue to the PR?

**Comment by senali-d** [comment]
> @senali-d can you please associate the issue to the PR?

@atapas Yeah sure. Done it.

**Comment by atapas** [comment]
@senali-d Can you please edit your play from the local dev and update the stream link in the video field? I can merge it after that.

**Comment by senali-d** [comment]
> @senali-d Can you please edit your play from the local dev and update the stream link in the video field? I can merge it after that.

@atapas yeah done it.

**Comment by senali-d** [comment]
> @senali-d Great Job. LGTM.
> 
> Do not forget to share it with the world.. and if you do so, please tag `#2PlaysAMonth` and `ReactPlayIO`.
> 
> Looking forward to the second one!

Yeah sure.

**Pull request merged**
