### PR TITLE
fix: random meme generator play was breaking due to broken api url

### PR DESCRIPTION
**Pull request by murtuzaalisurti**
# Description

Random meme generator play was breaking due to broken API url.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
@murtuzaalisurti Please create an issue for it and attach.

**Comment by murtuzaalisurti** [comment]
@atapas yep, sure

**Comment by murtuzaalisurti** [comment]
fixes #1151

**Comment by murtuzaalisurti** [comment]
@atapas linked the issue, you can merge it now!

**Review by atapas — APPROVED** [review]

**Pull request merged**
