### PR TITLE
[#2PlaysAMonth]: Smart Converter

### PR DESCRIPTION
**Pull request by AbhiPatel10**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Smart Converter is a comprehensive text handling solution that offers conversion and counting tools. It converts text into various formats, counts words and characters, and provides text manipulation tools like case conversion. The user-friendly interface makes it accessible for users of all skill levels

Implemented : #958 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

On Local System.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# Screenshots or example output

smartconcerter

### CODE REVIEW

**Comment by atapas** [comment]
Hi @AbhiPatel10 please associate he issue to the PR

**Comment by AbhiPatel10** [comment]
Already done sir it's #958 

Issue Number #958

**Comment by atapas** [comment]
> Already done sir it's #958
> 
> Issue Number #958

Not that!

You should always do this

image

**Comment by AbhiPatel10** [comment]
Sir I Don't have an option to add Issue here Please Guide me how Can I add ?

image

**Comment by atapas** [comment]
> Sir I Don't have an option to add Issue here Please Guide me how Can I add ?
> 
> image

I have added it.

**Comment by AbhiPatel10** [comment]
Okay Thank you sir, Looking forward to merge my PR. 😇

**Comment by atapas** [comment]
@AbhiPatel10 Correct the build error

image

**Comment by atapas** [comment]
@AbhiPatel10 ANy update on build fail fix?

**Comment by AbhiPatel10** [comment]
Okay, I haven't seen you commented here, I will solve this soon.

**Comment by atapas** [comment]
@AbhiPatel10 All looks good. Please record your stream on stack stream and add the video link by editing your play. Kindly post a message after that so that I can merge it.

**Comment by AbhiPatel10** [comment]
Okay Sure Sir. Thank you 👍

**Comment by atapas** [comment]
Hi @AbhiPatel10 have you done this? We want to merge it. Please add the recording.

**Comment by atapas** [comment]
Hi @AbhiPatel10 A reminder to add the recording for merge.

**Comment by AbhiPatel10** [comment]
Sorry for late sir, My health is really bad but I have recorded my play please go through this link.

https://www.stack-stream.com/v/introducing-smart-converter-play-for-2playsamonth

**Comment by atapas** [comment]
> Visit Preview

Oh I am sad to hear that @AbhiPatel10 . The recording looks great.

You need to add this recording link by editing the play. You can edit the play from the play header.

**Comment by AbhiPatel10** [comment]
Thank you sir 🙏

Done sir I have added play recording link in my play 🫡

**Review by atapas — APPROVED** [review]
@AbhiPatel10 Thanks for taking care of all the requests. Good to merge.

**Pull request merged**
