### PR TITLE
Added Weather play

### PR DESCRIPTION
**Pull request by ankitk26**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

* I have added a weather application to the plays where a user can enter a city or region and the weather conditions of the particular city are displayed. 
* The application also displays 5 days weather forecast for the given region.
* The weather data is fetched from OpenWeather API and it requires an API key. So the environment variable REACT_APP_WEATHER_API_KEY is to be added to the environment variables list.

image

Fixes # (issue)
#583 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

* No errors are shown for empty input search.
* An appropriate error message is shown if any invalid city name is searched.
* Several city names have been searched and all displayed correct output.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
Hi @ankitk26 

I was trying the app from the preview but it doesn't give me the result. Could you please check?

image

**Comment by atapas** [comment]
> Hi @ankitk26
> 
> I was trying the app from the preview but it doesn't give me the result. Could you please check?
> 
> image

If I am not wrong, you need to supply some environment variables like API ID for us to add to vercel. Please let us know, we will get it done.

**Comment by ankitk26** [comment]
Hi @atapas, we need to add an environment variable by the name 'REACT_APP_WEATHER_API_KEY' and set it equal to the API key from [OpenWeather API docs](https://home.openweathermap.org/api_keys)

**Comment by koustov** [comment]
> Hi @atapas, we need to add an environment variable by the name 'REACT_APP_WEATHER_API_KEY' and set it equal to the API key from [OpenWeather API docs](https://home.openweathermap.org/api_keys)

Hello @ankitk26 Can you generate a API key and pass to me so that I can get it added to the deployment

**Review by koustov — CHANGES_REQUESTED** [review]
I haven't done the review however, here are a couple of feedback from the preview build 
1. For better usability, the input box for the city name should be kind of `typeahead`
2. A wrong input should display appropriate error information. Currently, it just gets stuck on `Getting weather details...`
3.

**Comment by atapas** [comment]
> > Hi @atapas, we need to add an environment variable by the name 'REACT_APP_WEATHER_API_KEY' and set it equal to the API key from [OpenWeather API docs](https://home.openweathermap.org/api_keys)
> 
> Hello @ankitk26 Can you generate a API key and pass to me so that I can get it added to the deployment

@koustov let's generate it from the reactplay account. I have mailed you the key. Please add.

**Comment by koustov** [comment]
> > Hi @atapas, we need to add an environment variable by the name 'REACT_APP_WEATHER_API_KEY' and set it equal to the API key from [OpenWeather API docs](https://home.openweathermap.org/api_keys)
> 
> Hello @ankitk26 Can you generate a API key and pass to me so that I can get it added to the deployment

I am still getting unauthorized even after adding the env variable in deployment

**Comment by atapas** [comment]
> > > Hi @atapas, we need to add an environment variable by the name 'REACT_APP_WEATHER_API_KEY' and set it equal to the API key from [OpenWeather API docs](https://home.openweathermap.org/api_keys)
> > 
> > 
> > Hello @ankitk26 Can you generate a API key and pass to me so that I can get it added to the deployment
> 
> I am still getting unauthorized even after adding the env variable in deployment

Hi @ankitk26 Can we add your key and test?

**Comment by ankitk26** [comment]
> > > > Hi @atapas, we need to add an environment variable by the name 'REACT_APP_WEATHER_API_KEY' and set it equal to the API key from [OpenWeather API docs](https://home.openweathermap.org/api_keys)
> > > 
> > > 
> > > Hello @ankitk26 Can you generate a API key and pass to me so that I can get it added to the deployment
> > 
> > 
> > I am still getting unauthorized even after adding the env variable in deployment
> 
> Hi @ankitk26 Can we add your key and test?

My API key is abebbbc5ec9d34bf715ad5f12c8053f8.
Also just to be sure, the environment variable name is REACT_APP_WEATHER_API_KEY

**Comment by atapas** [comment]
@ankitk26 

It works now, great work,

One issue that in responsive mode the below texts are not readable

image

**Review by koustov — APPROVED** [review]
lgtm
@atapas  I am ok with the new responsiveness update. please merge if you are also aligned,

**Comment by ankitk26** [comment]
I just noticed that I interchanged the icon and value for humidity percentage and wind speed. So I fixed the mistake.

**Review by atapas — APPROVED** [review]

**Pull request merged**
