### PR TITLE
React Landing page

### PR DESCRIPTION
**Pull request by sidiDev**
# Description

Hi React play team! I was working on a simple, responsive and beautiful landing page with React and Float UI components, this play will help the beginners a lot to improve their knowledge of React

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

It's works correctly on my machIne with no errors or warnings in console

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@sidiDev this looks neat. Assigned for a review.

Early feedback, the changes are impacting the basic styles like H1...H6, some links, etc of the platform and so why impacting the look of other plays. It could be, that you are using Tailwind underneath and that is probably bringing some resets for those element styles. Could you please check once?

**Comment by koustov** [comment]
@sidiDev please create/assign an issue for this PR.

**Comment by atapas** [comment]
Hello @sidiDev  

We will be moving the react-play project from the `atapas` account to an organization to help manage the project in a better way. The new organization URL is: https://github.com/reactplay.

> **The movement will take place between 12:30 - 14:00 hrs IST(7:00 am - 8:30 am GMT), 30th May 2022. Please refrain from pushing any changes between this time.**

We will inform you when the movement is complete. You need to make a few minimal configuration changes after that. We will let you know.

**Comment by atapas** [comment]
> Hello @sidiDev
> 
> We will be moving the react-play project from the `atapas` account to an organization to help manage the project in a better way. The new organization URL is: https://github.com/reactplay.
> 
> > **The movement will take place between 12:30 - 14:00 hrs IST(7:00 am - 8:30 am GMT), 30th May 2022. Please refrain from pushing any changes between this time.**
> 
> We will inform you when the movement is complete. You need to make a few minimal configuration changes after that. We will let you know.

The migration is complete. You can find the project here: https://github.com/reactplay

You no need to reclone the project. You just need to set the correct upstream. Here is the link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

**Comment by sidiDev** [comment]
> > Hello @sidiDev
> > We will be moving the react-play project from the `atapas` account to an organization to help manage the project in a better way. The new organization URL is: https://github.com/reactplay.
> > > **The movement will take place between 12:30 - 14:00 hrs IST(7:00 am - 8:30 am GMT), 30th May 2022. Please refrain from pushing any changes between this time.**
> > 
> > 
> > We will inform you when the movement is complete. You need to make a few minimal configuration changes after that. We will let you know.
> 
> The migration is complete. You can find the project here: https://github.com/reactplay
> 
> You no need to reclone the project. You just need to set the correct upstream. Here is the link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

Ok tapas, thank you so much, I will check it out

**Comment by atapas** [comment]
@koustov Can you please review this one?

**Comment by sidiDev** [comment]
> @sidiDev
> 
> The tailwind support is in ReactPlay now. So you do not have to make any changes for this one: #281
> 
> Please pull the latest from the main, resolve merge conflicts. Let us review and get your play in.

Hi @atapas you can review my play now.

**Comment by koustov** [comment]
@sidiDev can you resolve the conflict, once done we can review/merge the PR.

**Comment by atapas** [comment]
> @sidiDev can you resolve the conflict, once done we can review/merge the PR.

@koustov Please finish the review.

**Comment by atapas** [comment]
Hi @sidiDev 

We have some massive changes in the data store and we are changing how the play gets created for a better usability. As this play is interim, we need to make sure it migrates correctly. Could you please ping me on Discord so that I make sure everything is placed?

https://discord.gg/YbmXwU5f

**Comment by sidiDev** [comment]
> Hi @sidiDev
> 
> We have some massive changes in the data store and we are changing how the play gets created for a better usability. As this play is interim, we need to make sure it migrates correctly. Could you please ping me on Discord so that I make sure everything is placed?
> 
> https://discord.gg/YbmXwU5f

Hi @atapas ! That's done mate.

**Comment by koustov** [comment]
Hello, @sidiDev I have taken a look at the play and it looks good to me however you need to resolve the conflicts (yet another time). Once done I can approve my end.

**Comment by sidiDev** [comment]
Hi! Thank you so much bro, but I'm sorry because I have a lot of works
these days, so I will do that later insh'Allah.

في الأربعاء، ١٣ يوليو ٢٠٢٢ ٧:٠٥ م Koustov ***@***.***> كتب:

**Comment by atapas** [comment]
Hey @sidiDev 

A reminder to get back on this play. This PR may be closed due to a lack of activities soon. Please let us know if you need any help.

Looking forward to getting the play in!

**Comment by Angryman18** [comment]
close this PR

**Comment by atapas** [comment]
Closing this PR as No Response for close to a couple of months. Please request to open if still working on it.

**Pull request closed without merging**
