### PR TITLE
[#2PlaysAMonth]: Video to MP3 Converter

### LINKED ISSUE #911: [#2PlaysAMonth]: Videos to MP3 converter
### What's the Play about?

An application that converts, YouTube videos to MP3 audio. 

### What ReactJS concept will be used to create this play?

- useState
- useRef 
- axios

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shivam-Katare**
# Description

**Tube2Tunes** is a user-friendly web application built in React that allows users to easily convert their favorite YouTube music videos to high-quality MP3 songs that can be downloaded for free.

Fixes #911 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# Screenshots or example output

Screenshot (764)
Screenshot (765)

# Demo Video

[Demo Video](https://www.stack-stream.com/v/introducing-tube-2-tunes-for-2-plays-a-month-3)

### CODE REVIEW

**Comment by atapas** [comment]
@Shivam-Katare Do we need the env update for this play?

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare Do we need the env update for this play?

Yes, @atapas. I will send you the env update on discord.

**Comment by atapas** [comment]
@Shivam-Katare 

image

- Add the event tag

- Add the stream recording link.

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
@Shivam-Katare Thank you for adding this project. LGTM.

**Comment by debjit** [comment]
Please investigate the legality of this type of application. I do not believe it is legal to convert a YouTube video to an MP3 file. Copywrite or legal issues may arise. Google does not host any chrome extension for converting YouTube videos to MP3 files.

**Comment by Shivam-Katare** [comment]
Hi @debjit, Yes you're right that google does not host any chrome extension for converting YouTube videos to MP3 files but, we will not lead this app to do violation. I searched about this and found some articles and answers on Quora.

It's can be true, they can be illegal. And TBH it is a tricky thing to understand so I get why people are confused.

The software is 100% legal, it’s just the way **WE** use it might not be.

………………………………….

Royalty-free / non-copyrighted material

- DOWNLOAD = Allowed
- RE-UPLOAD TO THE INTERNET = Allowed (quote the creator)
- Example -> NCS Music
………………………………….

Free copyrighted material (for example, any Bollywood songs on channels like(T-Series, Sony Music) )

DOWNLOAD = Allowed
RE-UPLOAD TO THE INTERNET = Not Allowed (Still, you can use their 30 seconds of clips(In form of video or mp3) on your youtube video(if you made any). And if you are not using any of their clips publicly then, it will not lead to the violation.

………………………………….

Paid copyrighted material (for example, a copyrighted song that you usually have to buy)

DOWNLOAD = Not Allowed
RE-UPLOAD TO THE INTERNET = Not Allowed (And this app also not supporting to download any paid youtube video)

- Last thing is, the apps that are currently present in the market that support this thing, support too many illegal ads and illegal content, and due to this we put them into the malware site category on the other side, this app does not contain any kind of malware or violated content thing. The app is purely made with React and the API that is used in this is also from Rapid API. So, there's no illegality in this app, and I mentioned this in Readme too.

**Pull request merged**
