### PR TITLE
675 feature request adding env file for dev mode during create react play process

### LINKED ISSUE #675: ✨ [Feature request]:  Adding .env file for dev mode during create-react-play process
We can create a .env file with the required dev setup details.
Also, we can update .gitignore not to check in this file.

This would be really helpful for any beginner.

### PR DESCRIPTION
**Pull request by ammaaraslam**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Added a `.env.development` file that contains all necessary environment variables required for local development. It is also not included in `.gitignore`.

Fixes #675 

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

# How Has This Been Tested?
Tested locally

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by atapas — APPROVED** [review]
LGTM

**Comment by koustov** [comment]
@ammaaraslam @atapas i am curios, this PR is called "during create react play process" however has been fixed on `react-play` repo. why so? also, you need a few other env variables to run the entire application properly, how do we plan to introduce them?

On the other hand, the `nhost` related information is not environment specific. These are constant across all environments. So why do we want to retain it within env file?

**Comment by atapas** [comment]
> @ammaaraslam @atapas i am curios, this PR is called "during create react play process" however has been fixed on `react-play` repo. why so? also, you need a few other env variables to run the entire application properly, how do we plan to introduce them?
> 
> On the other hand, the `nhost` related information is not environment specific. These are constant across all environments. So why do we want to retain it within env file?

It is not just for creating the play, it's also about setting up the base environment. Many issues come in the #needs-help channel asking, not able to see the plays in the dev mode, and folks are just missing the readme info to add those env properties.

So, these are "at least" items required for someone to set things locally.

Other env variables mostly play specifics, so we can add the keys with empty values for those. What do you think?

**Comment by ammaaraslam** [comment]
> > @ammaaraslam @atapas i am curios, this PR is called "during create react play process" however has been fixed on `react-play` repo. why so? also, you need a few other env variables to run the entire application properly, how do we plan to introduce them?
> > On the other hand, the `nhost` related information is not environment specific. These are constant across all environments. So why do we want to retain it within env file?
> 
> It is not just for creating the play, it's also about setting up the base environment. Many issues come in the #needs-help channel asking, not able to see the plays in the dev mode, and folks are just missing the readme info to add those env properties.
> 
> So, these are "at least" items required for someone to set things locally.
> 
> Other env variables mostly play specifics, so we can add the keys with empty values for those. What do you think?

Sorry for the late reply @koustov 
I think @atapas has given the best info on this PR.

The title might be throwing you off a little, cuz although the creator of the issue mentions "during create react play process", what they actually mean are the `env` variables we have mentioned in the `README.md`. So many newcomers tend to skip/forget that step of adding these which are essential to run the application locally.

And adding empty keys for play specific variables is a good choice as @atapas mentioned

**Pull request merged**
