### PR TITLE
Update code to clean eslint/prettier warnings and errors

### LINKED ISSUE #1239: Some errors happen when installation is done with a new package.json file ( dependencies version are not the same as the current reactplay )
When updating my dependencies ( eslint got problem currently in react-play when you use it with pnpm )
we got some errors :

image
Solution : 
   Comment this line in the file
___

image
Solution:
    Delete current in the import
___

image
Solution:
    delete the "event" variable in the onClick call.
___

image
Solution: 
    delete the "event" variable in the onClick call
___

image
Solution:
   delete the "event" variable in the onClick calls
___

image
Solution:
    Delete "plural" in the import
    Delete "resp" as a parameter in then()
___

image
Solution: 
     Delete the import for playHeader
     Delete the props in the function component
___

image
Solution:
     Comment "const [error, setError] = useState('');"
     Comment setError to console.log at line 45
___

image
Solution: 
    Comment "const data = structuringData[currState];"
___

image
Solution: 
   Don't import the useState at line 1
___

image
Solution:
    Don't assign the fetch to the const "promise"
    Don't assign the response result to the const "data"
___

image
Solution:
   Comment line 3 where the import is done
___

image
Solution:
    1- create a useState for "count" instead declaring it with let.
    2 - make it works ( trick the code )
___

image
Solution: 
  Don't use "e" in the HandleCardColor as it not called inside the function
___

image
Solution:
    Don't use event in the clickHandler function
___

image
Solution:
   use the variable "err" as a parameter of setError
___

image
Solution: 
    Comment the line import for "data"

### PR DESCRIPTION
**Pull request by Angra974**
# Description

When starting the application, some warnings come to us.
With new update of Eslint, these warnings come into errors and you can't continue to use the application.

So, this PR is intended to resolve these issues

Fixes #1239 

## Type of change

Delete unused variables.
As i've reverted back to the main branch, eslint configuration and an updated package.json files with eslint update inside was use.
In this case, some formatting was done in the same time than the correction for the unused variables.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Run pnpm lint
check for errors/warnings
Clean up errors/warnings
run pnpm lint
check for error/warnings

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
Capture d’écran du 2023-10-14 03-02-07

Capture d’écran du 2023-10-14 03-01-30

### CODE REVIEW

**Comment by priyankarpal** [comment]
@Angra974 please check the issue 
image

**Comment by Angra974** [comment]
Hi. I'm on it, just gone to take a little rest.
I think the problem is because the current version of eslint in the server was not the same on my computer.
When switching back to the main branch before creating a new one, i've stayed with the new version of estlint-prettier

I'm trying to install a clean directory before doing it again.

**Comment by Angra974** [comment]
Waiting for #1333 to be merged.

**Comment by Angra974** [comment]
> @Angra974 please check the issue image

Moved to https://github.com/reactplay/react-play/pull/1337
This one was closed and delete.

**Pull request closed without merging**
