### PR TITLE
selected author name displayed on dropdown

### LINKED ISSUE #836: 🐛 [Bug report]: Motivate Play filter dropdown is not showing the applied filter label
### Descrcibe the bug?

Motivate Play filter dropdown is not showing the applied filter label.

https://reactplay.io/plays/hat52/motivate-me

### Steps to reproduce the bug?

- Visit https://reactplay.io/plays/hat52/motivate-me
- Apply the author filter and it shows the `All` instead of the applied filter label.
image

### Expected behavior

Motivate Play filter dropdown should show the applied filter label.

### Desktop (Please provide your system information)

Browser [e.g. chrome]

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

image

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joeshajan**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

The selected author's name was not displayed in the dropdown as mentioned in the issue. So I fixed that.

Fixes #836

## Type of change

UI change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshots or example output

image

### CODE REVIEW

**Comment by atapas** [comment]
@Sachin-chaurasiya Can you please review this one?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Can you please review this one?

The changes look good, will verify the build preview and approve.

**Comment by Sachin-chaurasiya** [comment]
@joeshajan , Can we include the `All` option as well in the dropdown?
because there is no way to see all the quotes after selecting any author.

https://user-images.githubusercontent.com/59080942/209063434-94b0e093-26c3-4876-b283-a2ff9460d0e8.mp4

**Comment by joeshajan** [comment]
> @joeshajan , Can we include the `All` option as well in the dropdown? because there is no way to see all the quotes after selecting any author.
> 
>  Untitled.mp4

Sure

**Comment by joeshajan** [comment]
Hey, @Sachin-chaurasiya I have added **All** in dropdown. Is this what you meant?

image

**Comment by atapas** [comment]
@Sachin-chaurasiya Are we good with this?

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Are we good with this?

@atapas , We can merge this.

**Comment by atapas** [comment]
@Sachin-chaurasiya You need to explicitly approve for the merge.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya You need to explicitly approve for the merge.

Done ✅

**Review by atapas — APPROVED** [review]

**Pull request merged**
