### PR TITLE
Cleaning duplicate code in few .scss , .css files, imports

### LINKED ISSUE #758: 🐛 [Bug report]:  Duplicate code in various files.
### Descrcibe the bug?

Cleaning duplicate code in few .scss , .css files, imports and empty blocks. 

### Steps to reproduce the bug?

Go to the following files:

1. src/common/home/home.css
2. src/common/playcreated/play-created.scss
3. src/plays/calendar/Calendar.scss
4. src/plays/fun-quiz/QuizScreen.scss
5. src/plays/navbar/NavBar.css
6. src/common/header/HeaderNav.jsx
7. src/common/header/header.css
8. src/plays/image-gallery/Gallery.js

### Expected behavior

Duplicate lines of code should not exist.

### Desktop (Please provide your system information)

ios
chrome

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by trishnakalita660**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
Cleaned duplicate code in few .scss , .css files, imports and removed an empty .css file.
 
Fixes  #758

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by trishnakalita660** [comment]
Hi @atapas , Can you review?

**Comment by trishnakalita660** [comment]
@Sachin-chaurasiya Can you please review?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Can you please review?

Sure @trishnakalita660.

**Review by Sachin-chaurasiya — APPROVED** [review]
Thanks @trishnakalita660 , Changes Looks good to me.

**Comment by trishnakalita660** [comment]
@Sachin-chaurasiya  Can you help me in proving the details on how to merge this PR?

**Comment by trishnakalita660** [comment]
Hi @Sachin-chaurasiya Can you look into this? the Cypress Tests check passed successfully before.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Can you help me in proving the details on how to merge this PR?

@trishnakalita660 , It will need one review either from @atapas or @koustov, and then we can merge.

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya Can you look into this? the Cypress Tests check passed successfully before, but after "Merge branch 'main' into main" it failed.

I have re-run it.

**Comment by trishnakalita660** [comment]
@Sachin-chaurasiya Can you help me in merging this PR?

**Comment by trishnakalita660** [comment]
@atapas @koustov Can you please look into this PR as well? requires 2 approvals for merging I think.

**Review by atapas — APPROVED** [review]
Approving

**Pull request merged**
