### PR TITLE
Bug Fix for Issue #855

### LINKED ISSUE #855: 🐛 [Bug report]:  404 Page should redirect to home page
### Descrcibe the bug?

There are two issues
1. Currently 404 page says `Why don't you go back to home.. Redirecting in X sec.`. This is misleading as automatic redirection takes to `/plays` instead of home page
2. The text `home` should be hyperlinked with home page

### Steps to reproduce the bug?

1. Go to `reactplay.io`
2. Manullu update the url to something that doesn't exist in route table

### Expected behavior

As described in description

### Desktop (Please provide your system information)

Any

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Abhishek-90**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
This PR contains bug fix for redirecting users from `404 page` to `home page` when he navigates to any random URL. Originally it was navigating users to `plays page`.  

Fixes #855 

## Type of change
Bug Fix

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by Abhishek-90** [comment]
@atapas @koustov please review the PR.

**Comment by koustov** [comment]
@Abhishek-90  I noticed, today that when I clicked on the `Go Back` button, it went to the `home` page not the `plays` page. So is this issue still exist?
Try this https://reactplay.io/plays/deepak8717/dynamic-routes

**Comment by Abhishek-90** [comment]
> @Abhishek-90 I noticed, today that when I clicked on the `Go Back` button, it went to the `home` page not the `plays` page. So is this issue still exist? Try this https://reactplay.io/plays/deepak8717/dynamic-routes

I checked it, when I click on the `Go Back` button, it goes back to `/plays`

**Review by koustov — CHANGES_REQUESTED** [review]
@Abhishek-90  the fix looks good however this PR contains a few more changes that I couldn't find relevance,  Could you please remove those as they are not related to the associated defect

image

**Pull request closed without merging**
