### PR TITLE
Fixing banner promo issue

### PR DESCRIPTION
**Pull request by nirmalkc**
# Expectations

- [ ] Banner should be positioned at the top
- [ ] Banner should not overlap in both normal and other responsive viewports
- [ ] Banner should not overlap the responsive menu

# Screenshots or example output
image>

# Screenshot with normal view
image

### CODE REVIEW

**Comment by atapas** [comment]
@nirmalkc, the build fails. It's due to the lining errors

Please run these commands and then push only the file that you changed before:

- yarn format
- yarn lint
- yarn lint:fix

**Comment by niteshmodi** [comment]
can you please assign this to me

**Comment by atapas** [comment]
> Inspect



> can you please assign this to me

@nirmalkc its already been assigned to someone who is working on it. I have other cool issues to work on.. Catch me on Discord if you are interested in :)

**Review by atapas — APPROVED** [review]

**Comment by niteshmodi** [comment]
> 

What's your discord?

**Pull request merged**
