### PR TITLE
Fix 🐛 Bug #443 : Play snap is broken: Cover image is not appearing

### LINKED ISSUE #443: 🐛 [Bug report]: Play snap is broken: Cover image is not appearing
**Describe the bug**
When you share a play on any social media, the cover image is not appearing. Need to update the meta tag with appropriate cover image.

**To Reproduce**
1. Go to `reactplay.io`
2. List plays
3. Open any play which has a local cover image
4. Copy the URL
5. Paste the URL on social platforms/IMs

**Expected behavior**
The play should appear with name, description, creator and image

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I worked on fixing bug #443, Cover Image is not showing up when there is no cover image for the play in the database.
The fix will work like this,
If the cover is in DB then it will be shown, otherwise, we will look for the cover image in the play folder and if that is available it will be shown else default cover will be shown.

Fixes #443 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
1. Go to Any play
2. Copy the Play URL
3. Now share the Play URL
4. And see the preview cover

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@atapas @koustov, PR is ready for review.

**Review by koustov — DISMISSED** [review]
Looks good to me. @atapas can you make this build snap enabled to that we can test.

**Comment by atapas** [comment]
> Looks good to me. @atapas can you make this build snap enabled to that we can test.

It's already enabled

**Comment by atapas** [comment]
> > Looks good to me. @atapas can you make this build snap enabled to that we can test.
> 
> It's already enabled

@Sachin-chaurasiya did you have any success with the test? Codewise, I see all set actually. But when I tested it last time, the image was not showing up. Let's fix it/discuss.

cc: @koustov @Angryman18 please chime in with your ideas.

**Comment by Sachin-chaurasiya** [comment]
> > > Looks good to me. @atapas can you make this build snap enabled to that we can test.
> > 
> > 
> > It's already enabled
> 
> @Sachin-chaurasiya did you have any success with the test? Codewise, I see all set actually. But when I tested it last time, the image was not showing up. Let's fix it/discuss.
> 
> cc: @koustov @Angryman18 please chime in with your ideas.

Hey @atapas , No success, I tried a few other options too but no luck...

**Comment by koustov** [comment]
@Sachin-chaurasiya @atapas, I think I have fixed it. Shall I check in to this branch?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya @atapas, I think I have fixed it. I will check in to this branch instead of a new one.

Yeah @koustov, Please go ahead.

**Review by atapas — DISMISSED** [review]
LGTM

@koustov do a final review and merge plz.

**Comment by koustov** [comment]
@atapas we have some issues with vercel. It builds the meta tag with `localhost`. I have now modified the PR to work on the prod build **NOT** the preview build as a stop-gap measurement.
Can you get it merged, and then we can run one round of verification on the prod

**Comment by koustov** [comment]
> @atapas we have some issues with vercel. It builds the meta tag with `localhost`. I have now modified the PR to work on the prod build **NOT** the preview build as a stop-gap measurement. Can you get it merged, and then we can run one round of verification on the prod

image

**Review by koustov — APPROVED** [review]
lgtm

**Comment by Sachin-chaurasiya** [comment]
@atapas , awaiting for your approval.

**Review by atapas — APPROVED** [review]

**Pull request merged**
