### PR TITLE
✨ [Feature] #102: In filter modal creator dropdown should be a card list with image

### LINKED ISSUE #102: ✨ [Feature request]: In filter modal creator dropdown should be a card list with image
**Is your feature request related to a problem? Please describe.**
Currently, the creator dropdown is a flat list. It doesn't give enough context of the GitHub profile

**Describe the solution you'd like**
Use a contact card drop-down  instead

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- I worked on adding support for creator images in the creators select dropdown.
- For Consistency, I have changed the other select inputs to `@mui/material` `<Select/>` Component.
- Added fallback option if avatar URL is not present.

Fixes #102 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

https://user-images.githubusercontent.com/59080942/184501770-b64c336b-4269-43cc-993b-08a124cc077a.mov

image

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@koustov @atapas, PR is ready for review.

**Comment by atapas** [comment]
> @koustov @atapas, PR is ready for review.

@Sachin-chaurasiya We need to do something about the UI that list all the creators.. It seems to be very lengthy when it opens up. Can we put a scroll and limit the height?

**Comment by Sachin-chaurasiya** [comment]
> > @koustov @atapas, PR is ready for review.
> 
> @Sachin-chaurasiya We need to do something about the UI that list all the creators.. It seems to be very lengthy when it opens up. Can we put a scroll and limit the height?

Sure @atapas, I will look into it.

**Comment by Sachin-chaurasiya** [comment]
> > @koustov @atapas, PR is ready for review.
> 
> @Sachin-chaurasiya We need to do something about the UI that list all the creators.. It seems to be very lengthy when it opens up. Can we put a scroll and limit the height?

@atapas, I have fixed the height issue.
image

**Review by koustov — CHANGES_REQUESTED** [review]
@Sachin-chaurasiya this is definitely very cool however I see one challenge. As the names are not sorted and there is no filter, it will be very tough to find the intended creator as the list grows. So, can you 
- convert this control to typeahead or autocomplete
- sort the list by user name

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya this is definitely very cool however I see one challenge. As the names are not sorted and there is no filter, it will be very tough to find the intended creator as the list grows. So, can you
> 
> * convert this control to typeahead or autocomplete
> * sort the list by user name

@koustov , Can we do that in separate PR, because it will take more time and testing?
The main issue was to show the creator's profile picture and for that, I think PR is good enough.
Please create a ticket and assign it to me I will work on your suggestions.
cc : @atapas.

**Comment by koustov** [comment]
> 

Ok, I am approving this one. Let's get it thorough and create another one for update.

**Review by koustov — APPROVED** [review]
lgtm

**Comment by Sachin-chaurasiya** [comment]
@atapas , awaiting for your approval.

**Review by atapas — APPROVED** [review]

**Pull request merged**
