### PR TITLE
disable service worker on prod

### PR DESCRIPTION
**Pull request by Angryman18**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by koustov — CHANGES_REQUESTED** [review]
I am bti confused here. It was intended to disable service-worker in the non-prod environments however the changes made as per this PR, just flipped the concept. 
I mean, now SW will be enabled for all non-prod environments which were NOT the intention earlier. I do agree that it fixes the flickering issue however could you please explain the overall thought and consequences as well?

**Comment by atapas** [comment]
@Angryman18 Let's put this one in the "Draft" mode. We can spring it back to PR mode when we are sure, we need a review to merge.

**Comment by Angryman18** [comment]
yup sure.

**Comment by koustov** [comment]
Just made it `draft`

**Comment by atapas** [comment]
@Angryman18 What do we do about this one?

**Comment by Angryman18** [comment]
please assign this to someone else.

**Comment by Angryman18** [comment]
Donot beed this anymore

**Pull request closed without merging**
