### PR TITLE
[Bug Fix] : fix cypress test fail #866

### LINKED ISSUE #866: 🐛 [Bug report]: Fix the Cypress test fail issue
### Descrcibe the bug?

Now the Cypress test fails due to the Tweet card validation. Please fix it.

### Steps to reproduce the bug?

Run the Cypress build locally or see any preview build for the error log.

### Expected behavior

All tests should pass

### Desktop (Please provide your system information)

All

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roshan-Horo**
Fixed #866 

# Description

This PR is related to issue caused by running **Cypress on Github Actions**.

There are two issue related to that : 

1. **Timeout Issue while running Github Actions ( push, pull_request)** : The main issue here is cypress is waiting of default 30s or max 90s around to start development server. But the server not started yet. ( It takes around 180s to start )

image

  
**That's why cypress exit and test got failed**.

2. **Maybe some test case itself got failed** :  This is related to Issue #866, There are two observation that I find by running test locally 

-   when we test manually through cypress:open : we got all test passed

Screenshot (284)

-  But, when we test through cypress:run : 1 test got failed ( Tweet section )

cypress_run_error

# Fixes # (issue)

1. Fixing the 1st Issue with : 

SHORT TERM SOLUTION :  **Increase the waiting time period by 180 s** , I tested by running github actions locally and It takes around 180s to start the server and cypress will run it's tests. 

LONG TERM SOLUTION : Reduce the server starting time. ( I think Issue #578 ( Migrate from CRA to VITE ) solves this problem.

## Without wait-on-timeout
server_timeout

## With wait-on-timeout: 180
test_success

2. Test case 'Twitter Section ...' got failed : Running locally with cypress:run got failed but running with cypress:open and with github actions it got all tests passed. so, we can leave it there, if it's causing other problems then we can take this.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Through running Github Actions locally.

# Reference 

- Cypress timeout issue : https://github.com/cypress-io/github-action/issues/534
- wait-on-timeout example : https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml
- Running github actions locally : https://github.com/nektos/act

### CODE REVIEW

**Comment by swapn652** [comment]
So, this is why so many PR's have failed the checks.

**Comment by atapas** [comment]
@Roshan-Horo I need the issue number to merge.

**Comment by Roshan-Horo** [comment]
Hey @atapas, updated the issue no. in the PR description but the issue is in closed state.

**Comment by Angra974** [comment]
@atapas 
> @Roshan-Horo I need the issue number to merge.

Consider to add some config in cypress :
    "defaultCommandTimeout": 6000,
    "execTimeout": 60000,
    "pageLoadTimeout": 600000,
    "requestTimeout": 1500000,
    "responseTimeout": 1500000,

as the problem is more related to a slow network and the response time and the application itself ( slow by itself nevertheless ) .

**Comment by atapas** [comment]
> @atapas
> 
> > @Roshan-Horo I need the issue number to merge.
> 
> Consider to add some config in cypress : "defaultCommandTimeout": 6000, "execTimeout": 60000, "pageLoadTimeout": 600000, "requestTimeout": 1500000, "responseTimeout": 1500000,
> 
> as the problem is more related to a slow network and the response time than the application itself ( slow by itself nevertheless ) .

@Roshan-Horo have you checked this?

**Pull request closed without merging**
