### PR TITLE
Cra to vite

### LINKED ISSUE #1193: ✨ [Feature request]: Migrate from CRA to Vite
### Is your feature request related to a problem? Please describe.

ReactPlay currently uses CRA as its build tool, which is now considered to be far back from other available tools in terms of performance and its limitations.

### Describe the solution you'd like.

To tackle this, migrating the project from using CRA to Vite would address these problems and improve the overall development experience. Vite is much faster, more efficient and provides more tools to improve developer experience.

### Describe alternatives you've considered.

-

### Screenshot / Screenshare

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ammaaraslam**
# Description

This pull request encompasses the migration of the entire project from Create React App (CRA) to Vite. The migration was performed to leverage the benefits and improvements offered by Vite, aiming to enhance the development experience and improve overall performance.

**Project Setup**:
The project setup was updated to utilize Vite's build tooling and development server. The existing dependencies and configurations related to CRA were replaced with the corresponding Vite dependencies and configurations.

**Build System**:
The existing CRA build system based on webpack was replaced with Vite's native build system, which relies on the esbuild bundler. This change streamlines the build process, resulting in faster builds and optimized production bundles.

**Development Server**:
The CRA development server was replaced with Vite's fast development server, powered by esbuild. The new development server supports hot module replacement (HMR) and provides faster reloading and an improved developer experience.

**Configuration**:
The project's configuration files were updated to align with Vite's configuration structure. The "vite.config.js" file was introduced to specify custom build settings, plugins, and aliases.

**Comparisons**:
- Build Time: Vite significantly reduces build times by utilizing esbuild, resulting in faster and more efficient builds compared to the previous CRA setup.
- Development Experience: With Vite's development server and HMR capabilities, the development experience is improved, providing faster feedback loops and reducing waiting times during development iterations.
- Module Resolution: Vite's native ES module support improves module resolution, leading to more efficient bundling and better performance at runtime.
- Startup Time: Vite's optimized build process and dependency handling result in faster startup times for development and production builds.

---

**Changes to be made in terms of documentation and code in other repos**:

- [ ] Documentation must mention that the project uses Vite.
- [ ] Plays documentation must mention that any files created that has `jsx` elements within it, must be either of `.jsx`, `.ts` or `.tsx` file exension.
- [ ] Update the `create-react-play` cli to make sure that future plays are created as either `.jsx`, `.ts` or `.tsx` _(Issue has been created here [#38](https://github.com/reactplay/create-react-play/issues/38) )_

Fixes #1193 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Tested locally. Both building the app and running Cypress tests.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
Will start testing from tomorrow. I've a question @ammaaraslam 

Do you see improvement in developer experience in installing dependencies and running the local server?

**Comment by ammaaraslam** [comment]
> Will start testing from tomorrow. I've a question @ammaaraslam 
> 
> Do you see improvement in developer experience in installing dependencies and running the local server?

Yes.
I was I able to get nearly twice the speed in terms of running the local server, local build.
I've included the comparison in the description ☝️

**Comment by atapas** [comment]
@ammaaraslam We need to test the features. Have you started your sanilty?

**Comment by atapas** [comment]
@ammaaraslam the build fails with these.. please check. Aany build step to change?

7:13:08 PM: node_modules/@mui/system/GlobalStyles/GlobalStyles.d.ts(9,121): error TS2694: Namespace 'React' has no exported member 'JSX'.
7:13:08 PM: node_modules/@mui/system/cssVars/getInitColorSchemeScript.d.ts(42,100): error TS2694: Namespace 'React' has no exported member 'JSX'.
7:13:08 PM: node_modules/@react-leaflet/core/lib/attribution.d.ts(1,26): error TS7016: Could not find a declaration file for module 'leaflet'. '/opt/build/repo/node_modules/leaflet/dist/leaflet-src.js' implicitly has an 'any' type.
7:13:08 PM:   Try `npm i --save-dev @types/leaflet` if it exists or add a new declaration (.d.ts) file containing `declare module 'leaflet';`
7:13:08 PM: src/plays/quiz-app/types.ts(12,10): error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.
7:13:08 PM: src/plays/quiz-app/types.ts(12,18): error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.
7:13:08 PM: ​
7:13:08 PM: build.command failed                                        
7:13:08 PM: ────────────────────────────────────────────────────────────────
7:13:08 PM: ​
7:13:08 PM:   Error message
7:13:08 PM:   Command failed with exit code 2: CI= npm run build (https://ntl.fyi/exit-code-2)
7:13:08 PM: ​
7:13:08 PM:   Error location
7:13:08 PM:   In Build command from Netlify app:
7:13:08 PM:   CI= npm run build
7:13:08 PM: ​
7:13:08 PM:   Resolved config
7:13:08 PM:   build:
7:13:08 PM:     command: CI= npm run build
7:13:08 PM:     commandOrigin: ui
7:13:08 PM:     publish: /opt/build/repo/build
7:13:08 PM:     publishOrigin: ui
7:13:08 PM:   redirects:
7:13:08 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
7:13:08 PM: Failing build: Failed to build site
7:13:09 PM: Finished processing build request in 57.247s

**Comment by atapas** [comment]
We have merged a few PRs ... could you please pull the latest and do a sanity and let me know?

I will rest of the merges until this is merged. Also, consider any other doc changes.

**Comment by Angra974** [comment]
Hi @atapas 
Don't forget, we need this one validated first

https://github.com/reactplay/create-react-play/pull/41

to don't get problem with creating play in vite as for the moment, plays are still created with .js extension.

**Comment by joshi-kaushal** [comment]
Hi @ammaaraslam I need an update on this. Is it ready to merge? We need to plan further things accordingly.

**Pull request closed without merging**
