### PR TITLE
fixed empty notes adding bug 

### PR DESCRIPTION
**Pull request by Coderamrin**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
the notes gets added even if the not is empty. so, added a conditional on the handleSubmit function so that it prevent empty notes being added. 

Fixes # #993 

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
@Coderamrin Edit the description to add details like issue number. Also edit the title to be meaningful.

**Comment by Coderamrin** [comment]
> @Coderamrin Edit the description to add details like issue number. Also edit the title to be meaningful.

haven't raised a issue, do i add the play issue number?

**Comment by atapas** [comment]
> > @Coderamrin Edit the description to add details like issue number. Also edit the title to be meaningful.
> 
> haven't raised a issue, do i add the play issue number?

You need to raise a new issue explaining what it is abut?

**Comment by Coderamrin** [comment]
okay

**Comment by Coderamrin** [comment]
> > okay
> 
> @Coderamrin Have you created the issue?

yeah, check it out.

**Review by atapas — APPROVED** [review]

**Pull request merged**
