### PR TITLE
Added lib option to ts.config

### LINKED ISSUE #785: 🐛 [Bug report]: Master build fails due to new TypeScript methods being used
### Descrcibe the bug?

With the merge of PR #732, the master build fails due to a new TypeScript method that has been used in that PR which is not yet supported by the `react-play` configuration.

error-msg

### Steps to reproduce the bug?

- Clone/Fork the repo.
- Pull the latest changes
- Install packages - `npm install --legacy-peer-deps` or `yarn install`
- Build the application locally - `npm run build` or `yarn build`
- You should get the error.

### Expected behavior

The build should pass without spitting out the error.

### Desktop (Please provide your system information)

N/A

### Mobile (Please provide your device information)

N/A

### Screenshot / Screenshare

build-error-msg

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ammaaraslam**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

This PR includes the fix to the master build failing issue.
Fixes #785 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested on a local build.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by atapas — DISMISSED** [review]

**Comment by atapas** [comment]
Remove the snap and do a local build to see if it passes.

**Comment by atapas** [comment]
> @ammaaraslam
> 
> ## Creating an optimized production build...
> 14:54:25 | Failed to compile. 14:54:25 |   14:54:25 | TS2304: Cannot find name 'VoidFunction'. 14:54:25 | 10 | date: Date, 14:54:25 | 11 | event?: EventType, 14:54:25 | > 12 | onCancel: VoidFunction 14:54:25 | | ^^^^^^^^^^^^ 14:54:25 | 13 | } 14:54:25 | 14 | 14:54:25 | 15 | const CalendarEventForm = ({ date, event, onCancel }: Props) => { 14:54:25 |   14:54:25 |   14:54:25 | error Command failed with exit code 1. 14:54:25 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 14:54:25 | Error: Command "yarn run build" exited with 1

@ammaaraslam I found this for the above error: https://github.com/lukeed/uvu/issues/89

**Comment by atapas** [comment]
> > @ammaaraslam
> > ## Creating an optimized production build...
> > 14:54:25 | Failed to compile. 14:54:25 |   14:54:25 | TS2304: Cannot find name 'VoidFunction'. 14:54:25 | 10 | date: Date, 14:54:25 | 11 | event?: EventType, 14:54:25 | > 12 | onCancel: VoidFunction 14:54:25 | | ^^^^^^^^^^^^ 14:54:25 | 13 | } 14:54:25 | 14 | 14:54:25 | 15 | const CalendarEventForm = ({ date, event, onCancel }: Props) => { 14:54:25 |   14:54:25 |   14:54:25 | error Command failed with exit code 1. 14:54:25 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 14:54:25 | Error: Command "yarn run build" exited with 1
> 
> @ammaaraslam I found this for the above error: [lukeed/uvu#89](https://github.com/lukeed/uvu/issues/89)

Alternatively, we can change the type of these to void from the VoidFunction

image

**Review by koustov — CHANGES_REQUESTED** [review]
I guess no changes on CalendarEventForm and CalendarEventInfo files. Its only has prettier updates. 

If so please revert back them

**Review by koustov — APPROVED** [review]
lgtm

**Pull request merged**
