### PR TITLE
fix: overlapping icon over text

### LINKED ISSUE #1326: Fix : overlapping of icon over the text
### Is your feature request related to a problem? Please describe.

The "Become a Prime Sponsor" button has an issue , the icon in that while hovering overlaps the text .

Screenshot 2023-10-12 155838

### Describe the solution you'd like.

While hovering on the button the text and icon should not be overlapped but should be at a distance when hovered .

### Describe alternatives you've considered.

The icon and text should be at a correct distance when hovered is the only alternate solution i have found.

### Screenshot / Screenshare

Screenshot 2023-10-12 155838

### Additional context

i have already worked on it , please assign this to me .

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sa24miksha**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
This PR fixes the "Become a Prime sponsor" Button issue.  While hovering over the button , the handshaking heart icon was collapsing over the text written on it .
 1 file changed, 3 insertions(+), 5 deletions(-)

Fixes #1326 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Tested the application after fixing the issue , everything is working fine.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# Screenshots or example output

Screenshot 2023-10-12 182307

### CODE REVIEW

**Comment by priyankarpal** [comment]
@Sa24miksha this branch has conflict error please fix

**Comment by Sa24miksha** [comment]
@priyankarpal okay i will do that

**Comment by Sa24miksha** [comment]
Screenshot 2023-10-13 114438


this is the mobile view of the button

**Review by priyankarpal — APPROVED** [review]

**Comment by priyankarpal** [comment]
@atapas Please accept the build and verify if there are any changes required.

**Pull request merged**
