### PR TITLE
Contributors added

### PR DESCRIPTION
**Pull request by nobel10122025**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

i havent tested it. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by atapas — COMMENTED** [review]
Can we make the whole contribution list like a circle? Bigger one in the centre?

**Comment by nobel10122025** [comment]
> Can we make the whole contribution list like a circle? Bigger one in the centre?

i will try to make it as a circle

**Comment by atapas** [comment]
> > Can we make the whole contribution list like a circle? Bigger one in the centre?
> 
> i will try to make it as a circle

Here is one inspiration 😊

https://twitter.com/koustov/status/1554532551318212608?s=21&t=T6k_n2PNP2SI7Qr8b5TFIQ

**Comment by nobel10122025** [comment]
sorry sir, i am not able to created that circle shape. can i close this PR sir

**Comment by atapas** [comment]
> sorry sir, i am not able to created that circle shape. can i close this PR sir

If you got time, how about working together and making it happen? If you are interested, join our discord, let's brainstorm on how to build it and then proceed to implement and learn. Otherwise, always feel free to close the PR.

**Comment by nobel10122025** [comment]
> > sorry sir, i am not able to created that circle shape. can i close this PR sir
> 
> If you got time, how about working together and making it happen? If you are interested, join our discord, let's brainstorm on how to build it and then proceed to implement and learn. Otherwise, always feel free to close the PR.

yes sir sure, i get time only during weekends so i will try again and join the discord server

**Comment by atapas** [comment]
> > > sorry sir, i am not able to created that circle shape. can i close this PR sir
> > 
> > 
> > If you got time, how about working together and making it happen? If you are interested, join our discord, let's brainstorm on how to build it and then proceed to implement and learn. Otherwise, always feel free to close the PR.
> 
> yes sir sure, i get time only during weekends so i will try again and join the discord server

Sounds good 👍

**Comment by nobel10122025** [comment]
sorry sir, i wasnt able to figure out after spending hour. so i am closing the PR, i am sorry for wasting your time :(

**Pull request closed without merging**
