### PR TITLE
Update ideas.json

### PR DESCRIPTION
**Pull request by Programming-School-Pro-Coding**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Programming-School-Pro-Coding** [comment]
@atapas

**Comment by Programming-School-Pro-Coding** [comment]
Hey @atapas Please review

**Review by atapas — APPROVED** [review]

**Comment by Programming-School-Pro-Coding** [comment]
@atapas Can I delete the branch

**Comment by atapas** [comment]
> @atapas Can I delete the branch

Yes plz

**Comment by Programming-School-Pro-Coding** [comment]
> > @atapas Can I delete the branch
> 
> Yes plz

Done

**Comment by atapas** [comment]
@all-contributors please add @Programming-School-Pro-Coding  for Code

**Comment by atapas** [comment]
@all-contributors please add @Programming-School-Pro-Coding for code

**Pull request merged**
