### PR TITLE
fix: #1452 Testimonial card position

### LINKED ISSUE #1452: 🐛 [Bug report]:  Testimonial card position
### Descrcibe the bug?

need to fix testimonial card position check the screenshot 

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

kali 
brave 
latest

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

image

### Relevant log output

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Siddh744542**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

fixed the position of the Testimonial card position

Fixes #1452

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
image

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
few issues are there 
display `1920X1080`

Screenshot_2024-02-16_18_41_48

**Comment by Siddh744542** [comment]
Thanks for the reviewing my PR @priyankarpal, will update the changes soon

**Comment by Siddh744542** [comment]
@priyankarpal  changes done 

on larger screen : 
image


on smaller screen : 
image

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
