### PR TITLE
fixed canonical URL of website

### LINKED ISSUE #530: 🐛 [Bug report]: Canonical URL of website is set to the Vercel instance
**Describe the bug**

The canonical URL of the website in `index.html` is set to a Vercel subdomain, thus the search results rank this url higher than the actual one.

**To Reproduce**
1. Search reactplay in a search engine _(google, duckduckgo, etc)_.
2. You'll see the vercel assigned subdomain as the result.

**Expected behavior**
Instead of the Vercel subdomain, the actual URL, `https://reactplay.io` must be displayed.

### PR DESCRIPTION
**Pull request by ammaaraslam**
# Description

This PR fixes an issue with the canonical URL of the website.

Fixes #530 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested locally and a local build.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ammaaraslam** [comment]
The PR seems to have fixes the issue. @atapas and @koustov, please review and let me know what you think.

**Comment by atapas** [comment]
> The PR seems to have fixes the issue. @atapas and @koustov, please review and let me know what you think.

How did you confirm to test it?

**Comment by ammaaraslam** [comment]
> > The PR seems to have fixes the issue. @atapas and @koustov, please review and let me know what you think.
> 
> How did you confirm to test it?

I did a local build and it was working.

You can also view the source of the preview deploy to view the canonical url.

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
Looks good.

**Pull request merged**
