### PR TITLE
Redirect to 404 Page - working

### LINKED ISSUE #847: 🐛 [Bug report]: Not Redirect to 404 Page
### Descrcibe the bug?

If We enter wrong route then it's not redirect to 404 page.

### Steps to reproduce the bug?

Enter anything in route path which is not mentioned in routing and give enter.

It Look like this.

image

### Expected behavior

It's Should Look Like this.

image

### Desktop (Please provide your system information)

Windows
Chrome

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AbhiPatel10**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

When we entered anything in the route path, there was no 404 page, so I added one to the routing. 

Fixes #847 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Type anything in Route path  like `http://localhost:3000/playssdd`.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

image

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
@atapas sir and @koustov bro Please check this PR.

**Comment by atapas** [comment]
> @atapas sir and @koustov bro Please check this PR.

As I'm on vacation,it may take a bit longer. Will check soon.

**Review by koustov — APPROVED** [review]
lgtm

**Comment by koustov** [comment]
The 404 page still has some issues. I am not holding this PR for those issues, create a new one on #855

**Pull request merged**
