### PR TITLE
[Feature] : custom scroll bar

### LINKED ISSUE #1203: ✨ [Feature request]: Improve UX with Custom Scrollbar on Website
### Is your feature request related to a problem? Please describe.

The website currently uses the default scrollbar, which can be enhanced for a better user experience. 

### Describe the solution you'd like.

Requesting the implementation of a custom scrollbar in a visually appealing color to elevate the website's aesthetics. 
According to my preference, the color #00f2fe would suit well with the website's design. 

### Describe alternatives you've considered.

Changing the scrollbar color and size is the only alternative I have discovered

### Screenshot / Screenshare

need to change this

### Additional context

please assign it to me, I want to work on it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by letscodedanish**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

This PR add a new feature of custom scrollbar in a visually appealing color to elevate the website's aesthetics. The color #00f2fe suits well with the website's design.

Fixes #1203 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested manually on my local desktop.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

# Screenshots or example output

Screenshot (485)

### CODE REVIEW

**Comment by letscodedanish** [comment]
It fixes the scroll bar

**Review by priyankarpal — DISMISSED** [review]
Looks Good 🎉

**Comment by atapas** [comment]
Hey @letscodedanish Thanks for the contribution. It looks great. However, here is a small thing you want to take care. 

When there are too many items, the scroll handle becomes too small to observe.

image

**Comment by letscodedanish** [comment]
Okay I'll fix that @atapas

**Comment by letscodedanish** [comment]
@atapas scroll handle is fixed now.

**Comment by atapas** [comment]
> https://deploy-preview-1294--reactplayio.netlify.app/

There is something wrong. UI is not loading. Check the preview URL above.

**Comment by letscodedanish** [comment]
@atapas It's working fine on my system. Have a look.


https://github.com/reactplay/react-play/assets/112203113/d8d85113-8444-4d5d-aa80-9f2e667e0d45

**Comment by atapas** [comment]
> https://deploy-preview-1294--reactplayio.netlify.app/

Looks good.. I will close it today.

**Comment by atapas** [comment]
@priyankarpal please provide your review and approval.

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
