### PR TITLE
multiselect-component fix

### PR DESCRIPTION
**Pull request by yung-coder**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

I have tried to  fix the type errors in multiselect-component  play

## Type of change

- [✅] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

tested by me in my local system.

# Checklist:

- [ ✅] I have performed a self-review of my own code
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [ ✅] My changes generate no new warnings
- [ ✅] I have added tests that prove my fix is effective or that my feature works
- [✅ ] New and existing unit tests pass locally with my changes
- [ ✅] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
@yung-coder Which issue this PR for?

**Comment by yung-coder** [comment]
Actually it's linked to  plays folder cleanup issue specifically multi select-comp.

**Comment by yung-coder** [comment]
Updated @atapas can you please give it a look.

**Comment by atapas** [comment]
@yung-coder please pull, clean up node-Modules, do yarn and yarn start to test your changes are working fine... 

then push and let me know.

**Comment by yung-coder** [comment]
> @yung-coder please pull, clean up node-Modules, do yarn and yarn start to test your changes are working fine... 
> 
> then push and let me know.

Sure @atapas

**Comment by yung-coder** [comment]
@atapas i have removed react  from  .eslintrc.json 

but this is showing these errors
Screenshot from 2022-12-14 01-03-24

**Comment by yung-coder** [comment]
done @atapas

**Comment by atapas** [comment]
@yung-coder Please pull the main and make it ready.

**Comment by yung-coder** [comment]
Merged but it's breaking...?
@atapas

**Comment by atapas** [comment]
> Merged but it's breaking...?
> @atapas

What's breaking?

**Comment by yung-coder** [comment]
> > Merged but it's breaking...?
> > @atapas
> 
> What's breaking?

it has some conflicts with the base...?

**Comment by atapas** [comment]
> > > Merged but it's breaking...?
> 
> > > @atapas
> 
> > 
> 
> > What's breaking?
> 
> 
> 
> it has some conflicts with the base...?
> 
> 

Do you need help? Let's discuss in code clean up channel

**Comment by yung-coder** [comment]
I think as this branch is made from code clean-up branch which is 1 commit behind the main so it's conflicting...?

**Comment by atapas** [comment]
@yung-coder Do we need this PR?

**Comment by yung-coder** [comment]
No, you can discard it.
@atapas

**Pull request closed without merging**
