### PR TITLE
Improved PlayHeader(#1562)

### LINKED ISSUE #1562: ✨ [Feature request]: Improve PlayHeader
### Is your feature request related to a problem? Please describe.

1. When there is too much information in the play header, like long descriptions and not many tags, it becomes too large. The description stretches across the header, causing content to shift too far to the left. This creates layout problems where important elements, such as the dates are collapsing or overlapping.

image

2. When the play header contains too much information, such as tags and a lengthy description, the height of the header increases significantly. This reduces the available space for viewing the actual play content.

image

### Describe the solution you'd like.

For the first issue, we could set a maximum width for the description area in the play header.

For the second issue, we could add a "Collapse" button that folds the entire play header, leaving only essential elements like the back button, title, and icons (like/edit/share). When clicked, the button would toggle the full header view, allowing users to expand or collapse it based on their preference, ensuring they can focus on the play content.

image

**NOTE**: Feel free to suggest any other ideas you believe are effective. The above solutions are just suggestions.

### Describe alternatives you've considered.

No alternative.

### Screenshot / Screenshare

_No response_

### Additional context

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [X] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joshua-jinu**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Fixes #1562 

- Added max-width for the description.
- Implemented collapse button using useState and useContext to display only the relevant information.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran the code locally on my system, manual testing. Checked for functionality and responsiveness across different windows and pages. Ran linter to check for any lint issues.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

image

image

### CODE REVIEW

**Comment by priyankarpal** [comment]
@joshua-jinu Can we enhance the button?

> Implemented collapse button using useState and useContext to display only the relevant information.

**Comment by joshua-jinu** [comment]
Sure, any suggestions you have in mind?

**Comment by joshua-jinu** [comment]
Sure, any suggestions you have in mind?
> @joshua-jinu Can we enhance the button?
> 
> > Implemented collapse button using useState and useContext to display only the relevant information.

**Comment by priyankarpal** [comment]
> Sure, any suggestions you have in mind?
> 
> > @joshua-jinu Can we enhance the button?
> > > Implemented collapse button using useState and useContext to display only the relevant information.

I have one idea: a black border without a black background. Let's see if this works; if not, we'll use the first one.

**Comment by joshua-jinu** [comment]
Done @priyankarpal, do check it out and let me know of any required changes

image

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
