### PR TITLE
Simple live chat UI break repair .

### PR DESCRIPTION
**Pull request by yung-coder**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Here I have tried to fix the CSS break in  simple  live chat  UI  by doing some changes in the CSS file

Fixes   react-play#325 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

It has been tested by me in my local system in all  edge cases 

Here's how it looks after my changes 

fix

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@Angryman18 You may want to review this one!

**Comment by Angryman18** [comment]
we need to deployed domain authorized on the firebase otherwise firebase will intercept requests from this domain. we can delete once the pull request goes off

**Comment by yung-coder** [comment]
Will this require any input from my side ..

**Comment by atapas** [comment]
@yung-coder It should be working now. Please check the preview URL and test.

**Comment by yung-coder** [comment]
Where can I find preview url ..?

**Comment by Angryman18** [comment]
LGTM

**Comment by atapas** [comment]
> Where can I find preview url ..?

Right here in your PR

https://github.com/reactplay/react-play/pull/331#issuecomment-1160487615

**Review by atapas — APPROVED** [review]

**Pull request merged**
