### PR TITLE
Navbar filter bug fix

### LINKED ISSUE #302: 🐛 [Bug report]: Filter box appear on landing page of the application
**Describe the bug**
The filter box appears on the application's landing page for a fraction and then vanishes. Refer screenshot

**To Reproduce**
1. Go to '[reactplay](https://reactplay.io/)'
2. Refresh the page

**Expected behavior**
The filter box should only appear when one navigates to [play](https://reactplay.io/plays) page

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ShivamBhasin2002**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #302 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by koustov** [comment]
@ShivamBhasin2002 please link this PR to an issue.

**Review by koustov — APPROVED** [review]
LGTM
Please assign the issue

**Comment by ShivamBhasin2002** [comment]
yeah @koustov #302

**Comment by koustov** [comment]
> yeah @koustov #302

As of now, I have attached it. 

image

image


Just make sure we link it while we are creating the PR

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
@all-contributors please add @ShivamBhasin2002 for Code

**Pull request merged**
