### PR TITLE
Netlify Img Added in footer

### PR DESCRIPTION
**Pull request by Saurav-Pant**

### CODE REVIEW

**Comment by atapas** [comment]
@Saurav-Pant I can not merge it without an issue number. Please provide it.

**Comment by priyankarpal** [comment]
@Saurav-Pant may I offer a suggestion? Adding a descriptive title and a clear description of the issue, along with relevant screenshots if possible & with the issue number would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.

**Comment by Saurav-Pant** [comment]
> @Saurav-Pant I can not merge it without an issue number. Please provide it.

#1116 is the issue Number

**Comment by Saurav-Pant** [comment]
> @Saurav-Pant may I offer a suggestion? Adding a descriptive title and a clear description of the issue, along with relevant screenshots if possible & with the issue number would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.

Thanks, I will do it Next Time.

**Comment by atapas** [comment]
> @Saurav-Pant may I offer a suggestion? Adding a descriptive title and a clear description of the issue, along with relevant screenshots if possible & with the issue number would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.

Yes! We need to talk more about these in our community Catch up call. @priyankarpal You may want to take it up on the next meeting.

**Review by atapas — APPROVED** [review]

**Comment by priyankarpal** [comment]
Ok

**Pull request merged**
