### PR TITLE
Add Eslint, prettier and pre commit hook.

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
DO NOT MAKE ANY CHANGES TO THIS PR

**Comment by joshi-kaushal** [comment]
hi @Sachin-chaurasiya! I was already working on the same issue. The work was on halt on PR https://github.com/reactplay/react-play/pull/507.

**Comment by Sachin-chaurasiya** [comment]
> hi @Sachin-chaurasiya! I was already working on the same issue. The work was on halt on PR https://github.com/reactplay/react-play/pull/507.
> 

@joshi-kaushal , I think it will have a lot of changes and will be hard to manage, that's why I created separate PR and I have resolved a bunch of issues.

**Comment by joshi-kaushal** [comment]
Yes. That's why we decided to split this issue into two separate pull requests. First PR will configure the project and the other will solely focus on fixing linting/prettier issues from the existing codebase.

**Comment by Sachin-chaurasiya** [comment]
> Yes. That's why we decided to split this issue into two separate pull requests. First PR will configure the project and the other will solely focus on fixing linting/prettier issues from the existing codebase.

@joshi-kaushal , I think we should sync up on this and decide how to approach this thing.

**Comment by joshi-kaushal** [comment]
Of course. Let's have a meeting sometime this week.

**Comment by Sachin-chaurasiya** [comment]
As discussed this PR will be the second patch for eslint and a prettier fix after we have merged the #507.
I will push the updated eslint and prettier config in #507.

**Pull request merged**
