### PR TITLE
Fixed: Play header is missing from Text Avatar play

### PR DESCRIPTION
**Pull request by hiimnhan**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Fix https://github.com/reactplay/react-play/issues/650

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hiimnhan** [comment]
Ready to review

**Review by atapas — APPROVED** [review]
Thanks @hiimnhan for fixing it quick.

@Sachin-chaurasiya I am good with this.. approving. Please test/review and approve.

**Comment by Sachin-chaurasiya** [comment]
> Thanks @hiimnhan for fixing it quick.
> 
> @Sachin-chaurasiya I am good with this.. approving. Please test/review and approve.

Sure @atapas.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by atapas** [comment]
@all-contributors please add @hiimnhan for Code

**Pull request merged**
