### PR TITLE
PR - Fixed The Activites After Auth

### PR DESCRIPTION
**Pull request by chhakuli123**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

After auth play was not getting liked because in nhost intializating it requires subdomain and region.

Fixes # (issue)

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by chhakuli123** [comment]
Hi @priyankarpal 
How can I see live preview of this PR
image

**Comment by priyankarpal** [comment]
> Hi @priyankarpal How can I see live preview of this PR image

now you can check. We(maintainers) have to accept the deployment after you can see the deployed site.

**Review by priyankarpal — CHANGES_REQUESTED** [review]
there is an error please check 
image

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by chhakuli123** [comment]
> Looks Good 🎉

Is feature working after auth?

**Comment by priyankarpal** [comment]
> > Looks Good 🎉
> 
> Is feature working after auth?

yes

**Review by joshi-kaushal — APPROVED** [review]

**Comment by priyankarpal** [comment]
@all-contributors please add @chhakuli123 for code

**Pull request merged**
