### PR TITLE
fix #680: umami and nhost svg colour change

### LINKED ISSUE #680: 🐛 [Bug report]: nHost and umami svg not grey colour in tech stacks page
**Describe the bug**
In tech stacks page nHost and umami svg does not have uniform colour like others.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://reactplay.io/tech-stacks'
2. Can see the colour difference 

**Expected behaviour**
**Screenshots**
Screenshot 2022-10-11 at 7 07 12 PM
Screenshot 2022-10-11 at 7 05 29 PM

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [ chrome, safari]
 - Version [22]

**Additional context**
Like to work on this. Could you assign me to this?

### PR DESCRIPTION
**Pull request by SSK-14**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
Change nHost and umami svg colour to grey.

Fixes # (680)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Angryman18** [comment]
on hover make icon change its color as it happens hovering over other icons.

**Comment by SSK-14** [comment]
> on hover make icon change its color as it happens hovering over other icons.

Have added filters while hover and changed the colour like others.

**Comment by Angryman18** [comment]
LGTM

**Review by Angryman18 — APPROVED** [review]

**Review by atapas — APPROVED** [review]
Accepting.

**Pull request merged**
