### PR TITLE
Issue 408 rename readme for qr code generator

### LINKED ISSUE #408: 🐛 [Bug report]: QR Code Generator : readme link is broken
**Describe the bug**
For QR code generator, the link for the readme file is broken.

**To Reproduce**
- Open reactplay.io
- `Browse` all plays
- Locate and open `QR Code Generator`
- Click on the link for readme file

**Expected behavior**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by koustov**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #408 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by atapas — APPROVED** [review]
Changes are fine but the project doesn't have a Readme file. That needs to be fixed separately.

@murtuzaalisurti

**Comment by murtuzaalisurti** [comment]
I added the readme file when I made a PR. I don't know how it's not evident, need to check.

**Comment by atapas** [comment]
> I added the readme file when I made a PR. I don't know why it's not evident, need to check.

It's fine now.

**Comment by murtuzaalisurti** [comment]
is it fixed or do I need to?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by atapas** [comment]
> is it fixed or do I need to?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question  |  **Tags:** Not reusable

Fixed. Check one on prod

**Comment by murtuzaalisurti** [comment]
cool

**Pull request merged**
