### PR TITLE
Issue 668 add a share button on typing speed play

### LINKED ISSUE #668: ✨ [Feature request]: Add a share button on Typing Speed Play
**Is your feature request related to a problem? Please describe.**
When i generate my typing speed report i would like to be able to share it with others.

**Describe the solution you'd like**
Add a share/ copy link button on the modal showing my typing speed.

**Describe alternatives you've considered**

**Additional context**
thinking of using the twitter API for this feature.

### PR DESCRIPTION
**Pull request by bhtibrewal**
# Description

- Customised Social Share component so that it can be reused here.
- Added the Social Share component to ResultModal.js 

Fixes #668 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Do the Typing Speed test and then click on the twitter icon to post the result on twitter.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
Screenshot 2022-10-14 at 12 38 52 AM
Screenshot 2022-10-14 at 12 39 20 AM

### CODE REVIEW

**Comment by bhtibrewal** [comment]
@atapas plz review this the PR is very small... Thanks

**Comment by atapas** [comment]
@bhtibrewal fix the build fail

image

**Comment by bhtibrewal** [comment]
> @bhtibrewal fix the build fail
> 
> image

please check now @atapas

**Comment by atapas** [comment]
Hey @bhtibrewal How to trigger this tweet? I am not seeing the option in the UI. Can you please post screenshots?

**Comment by bhtibrewal** [comment]
> Hey @bhtibrewal How to trigger this tweet? I am not seeing the option in the UI. Can you please post screenshots?

image
here it is tapas when you complete the typing test you see a twitter logo in the result modal

**Review by ammaaraslam — CHANGES_REQUESTED** [review]
@bhtibrewal
I think it'd be nice to have the share button before the "Try Again" button and make the share button a bit smaller, add some spacing between it and the "Try Again" button.

**Comment by koustov** [comment]
> @bhtibrewal I think it'd be nice to have the share button before the "Try Again" button and make the share button a bit smaller, add some spacing between it and the "Try Again" button.

On a similar line, the share button doen't give the impression of it. My suggestion would be to create a similar button like `Try again` (maybe with different color) and place them side by side. Also make the share button text as `Share <Twitter Icon>` or just the icon

**Review by koustov — CHANGES_REQUESTED** [review]
Comment posted already

**Comment by bhtibrewal** [comment]
@koustov I have updated the share button styling can u plz look into it

**Review by koustov — APPROVED** [review]
lgtm

**Review by ammaaraslam — APPROVED** [review]
All looks great!

**Comment by bhtibrewal** [comment]
@ammaaraslam can u plz add hacktoberfest tags to this pr, thanks for the approval @koustov and @ammaaraslam

**Pull request merged**
