### PR TITLE
Updated code for dynamic banner and playlist for a better user experi…

### PR DESCRIPTION
**Pull request by Angra974**
…ence

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

Fixes https://github.com/reactplay/react-play/issues/1064
Fixes https://github.com/reactplay/react-play/pull/1075

# Description

The current playlist has 5 steps we can count to display the playlist page.
2 of these steps are repeated. 
With some modification, we can take these 2 steps.

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Take of randomIndex, as it's a value just use to get a random index, no need to use a state for it, and we can just add it 
in the display banner. It seems to have an incidence on the homepage as if we let it and console.log in the component, we can have a console.log less without this useState.

Sometimes, on the website, we have a "loading..." that can be on the page. It's because the banner is not found, and the code goes to the catch error. 
As the loading is not set to false here, the message keeps showing itself. 
The code resolves this issue too.

 The logic with if/else in the component is to be sure that if a condition is not met, no render is done.
So you can't have the loader and at the same time the dynamic banner if no play.

No typecasting, the plays are directly defined as an array, and not null so we have no problem using the length properties on it. 

Redefine the key in the map for the playlist as the index is not a good practice and leed to some errors. 
Take off the fragment in the map as they are not needed.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
1/ Downloaded the last version of ReactPlay online to work with.
2/ Made modifications in src/common/playlists./PlayList.jsx and DynamicBanner.jsx. Dynamic banner is only used in PlayList
3/ Compared result behavior with the online website (view screencast ) before change with online/local and after modifications on local.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Compared behavior of online websites with local.
Tested search with name and filters. 
Go back from play.
Cancel Search by name ( click on X ).

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings and fewer react error
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output 
https://watch.screencastify.com/v/4Ysc9Fud8vz3zz1ICqeK

### CODE REVIEW

**Comment by priyankarpal** [comment]
This brach has conflicts error. PLease resolve it

**Comment by Sachin-chaurasiya** [comment]
@Angra974 , Build is failing, can you check?
image

**Comment by Angra974** [comment]
> > > @Angra974 , Build is failing, can you check? image
> > 
> > 
> > Look where the change was made. No relation with code in plays.
> 
> The branch need to be updated from main

I'm on some push tonight. Will refresh this one.

**Comment by Angra974** [comment]
Closed the PR as i started a new one. Get the plays mixed in the push so i created a clean one.

**Pull request closed without merging**
