### PR TITLE
Weather app for hackoctober fest

### PR DESCRIPTION
**Pull request by irfanmit**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Hi, this is my first pull request to any open source repo...this is a simple weather app that will display weather condition of any searched city

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

There is no issue i have solved..i had added my own code

## Type of change

Included FaisalPlay named weather app

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have verified my code properly and this works well...there is no bug and issue 

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
WhatsApp Image 2023-10-02 at 5 29 23 PM

### CODE REVIEW

**Comment by priyankarpal** [comment]
@irfanmit issue no?

**Comment by irfanmit** [comment]
> @irfanmit issue no?

yep i have verified the code works well.. i have screenshot attached you can check

**Comment by priyankarpal** [comment]
> > @irfanmit issue no?
> 
> yep i have verified the code works well.. i have screenshot attached you can check

Can you please let me know the issue number? And did you make the issue before creating the PR?

**Comment by irfanmit** [comment]
> > > @irfanmit issue no?
> > 
> > 
> > yep i have verified the code works well.. i have screenshot attached you can check
> 
> Can you please let me know the issue number? And did you make the issue before creating the PR?

Yes that was for because i was not able to create new play(from create play button i have screenshot attached too in the issue)....well this is my first contributing so i may do silly stuff i apologize for that

**Comment by irfanmit** [comment]
> > > > @irfanmit issue no?
> > > 
> > > 
> > > yep i have verified the code works well.. i have screenshot attached you can check
> > 
> > Can you please let me know the issue number? And did you make the issue before creating the PR?
> 
> Yes that was for because i was not able to create new play(from create play button i have screenshot attached too in the issue)....well this is my first contributing so i may do silly stuff i apologize for that
> ISSUE NO - #1273
> 

Issue no is #1273

**Comment by priyankarpal** [comment]
> > > > > @irfanmit issue no?
> > > > 
> > > > 
> > > > yep i have verified the code works well.. i have screenshot attached you can check
> > > 
> > > 
> > > Can you please let me know the issue number? And did you make the issue before creating the PR?
> > 
> > 
> > Yes that was for because i was not able to create new play(from create play button i have screenshot attached too in the issue)....well this is my first contributing so i may do silly stuff i apologize for that
> > ISSUE NO - #1273
> 
> Issue no is #1273

I got it. so there is already a PR related to the Weather APP so try to avoid adding duplicate PRs. You can add another project

**Comment by irfanmit** [comment]
> > > > > > @irfanmit issue no?
> > > > > 
> > > > > 
> > > > > yep i have verified the code works well.. i have screenshot attached you can check
> > > > 
> > > > 
> > > > Can you please let me know the issue number? And did you make the issue before creating the PR?
> > > 
> > > 
> > > Yes that was for because i was not able to create new play(from create play button i have screenshot attached too in the issue)....well this is my first contributing so i may do silly stuff i apologize for that
> > > ISSUE NO - #1273
> > 
> > 
> > Issue no is #1273
> 
> I got it. so there is already a PR related to the Weather APP so try to avoid adding duplicate PRs. You can add another project

Last PR i had closed it because the description i had not made it properly....so i made another PR with correct description and with same project , well is that a problem?

**Comment by priyankarpal** [comment]
> > > > > > > @irfanmit issue no?
> > > > > > 
> > > > > > 
> > > > > > yep i have verified the code works well.. i have screenshot attached you can check
> > > > > 
> > > > > 
> > > > > Can you please let me know the issue number? And did you make the issue before creating the PR?
> > > > 
> > > > 
> > > > Yes that was for because i was not able to create new play(from create play button i have screenshot attached too in the issue)....well this is my first contributing so i may do silly stuff i apologize for that
> > > > ISSUE NO - #1273
> > > 
> > > 
> > > Issue no is #1273
> > 
> > I got it. so there is already a PR related to the Weather APP so try to avoid adding duplicate PRs. You can add another project
> 
> Last PR i had closed it because the description i had not made it properly....so i made another PR with correct description and with same project , well is that a problem?



see there is already a pr for `weather app` so it's better to avoid to add another `weather app`. you can add another project by creating a new issue & pr

**Comment by irfanmit** [comment]
Meaning I close this PR and make another project because someone already making a PR of weather app

**Comment by priyankarpal** [comment]
> Meaning I close this PR and make another project because someone already making a PR of weather app..is it?

yes

**Pull request closed without merging**
