### PR TITLE
Nabendu shader project

### PR DESCRIPTION
**Pull request by nabendu82**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Added a new play for Animated shaders using React Fiber

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Done

# Checklist:

- [Y] I have performed a self-review of my own code
- [Y] I have commented my code, particularly in hard-to-understand areas
- [Y] I have made corresponding changes to the documentation
- [Y] My changes generate no new warnings
- [Y] I have added tests that prove my fix is effective or that my feature works
- [Y] New and existing unit tests pass locally with my changes
- [Y] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

https://res.cloudinary.com/dxkxvfo2o/image/upload/v1696397131/animated_akur2i.png

### CODE REVIEW

**Comment by joshi-kaushal** [comment]
hi @nabendu82! Thanks for your contribution :D
Could you please mention which issue does it solve?

**Comment by nabendu82** [comment]
This is not a issue, but a new play.

**Comment by joshi-kaushal** [comment]
@nabendu82 Yes. But you first need to create an issue on [this page](https://github.com/reactplay/react-play/issues) and get yourself assigned to it before you start working on it. It's a protocol that we follow to keep everything streamlined.

**Comment by Sachin-chaurasiya** [comment]
Hello @nabendu82 , there is a conflict, can you please resolve that? if you need any help then you can reach out in discord, thanks!

**Pull request closed without merging**
