### PR TITLE
 Changes to be committed: Added Cheesy Pick-up lines Play

### LINKED ISSUE #1534: [Add a Play]:  Add Cheesy Lines Randomizer to Display Random Pick-Up Lines
### What's the Play about?

This issue introduces the **Cheesy Lines Randomizer**, a React-based play that generates random cheesy pick-up lines each time a user clicks the button. The randomizer function selects from a collection of witty and lighthearted pick-up lines, ensuring a fresh line is shown with every interaction, making the experience fun and dynamic.

### ReactJS Concepts Used in Cheesy Lines Randomizer

In this project, the **Cheesy Lines Randomizer** play utilizes several key **ReactJS concepts** to deliver its functionality:

1. **State Management (`useState`)**:
   - The `useState` hook is used to manage the displayed pick-up line. Each time the user clicks the button, the state updates with a new random line from the collection, ensuring a dynamic user experience.

2. **Event Handling**:
   - React’s event handling is implemented to trigger a function when the "Get Cheesy Line" button is clicked. The `onClick` event fires a randomizer function to generate a new line.

3. **Component Rendering**:
   - The component will dynamically render the random pick-up lines based on the state. Whenever the state changes, the displayed line is updated in real-time.

4. **JSX**:
   - JSX is used to structure the layout of the play, including the button and the display area for the pick-up lines, making the app both interactive and visually appealing.

These ReactJS concepts allow the **Cheesy Lines Randomizer** to provide an engaging and seamless user experience by responding to input and dynamically updating the interface.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Karna0005**
new file:   src/plays/cheesylines/Cheesylines.js
	new file:   src/plays/cheesylines/Readme.md

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

Fixes #1534 

#HACTOBERFEST

### Pull Request Title: Add Cheesy Lines Randomizer Feature to Display Random Pick-Up Lines

---

### Description:

This pull request addresses the issue of implementing the **Cheesy Lines Randomizer** feature. The play is a React-based interactive web application that generates random cheesy pick-up lines when a button is clicked.

---

### Key Features:

1. **Randomizer Functionality:**
   - A random pick-up line is generated and displayed from a predefined collection when the user clicks the "Get Cheesy Line" button.

2. **React Concepts Used:**
   - **State Management (`useState`)**: Manages the currently displayed pick-up line.
   - **Event Handling**: The `onClick` event on the button triggers the randomizer function.
   - **Component Rendering**: Updates the displayed line in real-time based on the current state.
   - **JSX Layout**: Structurally displays the lines and button in a clean, interactive design.

3. **UI/UX:**
   - A responsive and minimalist interface designed to work on different screen sizes, featuring an eye-catching button and neatly formatted display of pick-up lines.

---

### How to Test:

1. Clone the repository and switch to the branch containing this feature.
2. Run `npm install` to install all dependencies.
3. Start the application by running `npm start`.
4. Interact with the app by clicking the "Get Cheesy Line" button to display random pick-up lines.

---

### Linked Issue:

This pull request addresses and closes **Issue #[#1534]** - "Add Cheesy Lines Randomizer to Display Random Pick-Up Lines".

---

### Checklist:
- [x] Implemented the randomizer function.
- [x] Styled the user interface for an engaging experience.
- [x] Verified that the randomizer works and updates the displayed line dynamically.
- [x] Tested responsiveness across different devices and screen sizes.

---

Feel free to reach out on Discord for further discussions or feedback on this feature!

# Screenshots
Screenshot (20)
Screenshot (19)

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
there is something wrong with css please check  

Screenshot_2024-10-09_10-24-48

**Comment by Karna0005** [comment]
**it is absolutely fine.** 

Screenshot (21)

**Review by priyankarpal — CHANGES_REQUESTED** [review]
please check another play once

image

**Comment by Karna0005** [comment]
hey, I have changed the css please verify!

**Comment by Karna0005** [comment]
can anyone tell me what's wrong with the code..? please

**Comment by priyankarpal** [comment]
> can anyone tell me what's wrong with the code..? please

now it's ok

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
