### PR TITLE
Search bar issue when u open search bar in mobile its not responsive …

### PR DESCRIPTION
**Pull request by RanaZaeem0**
…#1495

hi
by adding some css properties the search filter is became responsive on all device

### CODE REVIEW

**Review by priyankarpal — COMMENTED** [review]
hello @RanaZaeem0, in the future, try to create Pull Requests from a different branch instead of creating them from the `main` branch.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by RanaZaeem0** [comment]
I am sorry it was my first I will take care in future

**Comment by priyankarpal** [comment]
> I am sorry it was my first I will take care in future

no issue

**Pull request merged**
