### PR TITLE
fix: search bar responsiveness mobile view

### LINKED ISSUE #1354: 🐛 [Bug report]: Fix search bar in mobile view
### Descrcibe the bug?

Currently, the search bar in mobile view looks so compact and after searching any term, the close and the filter icon takes up the whole space.

### Steps to reproduce the bug?

1. Go to https://reactplay.io/plays
2. Search any play using search bar
3. Switch to mobile view and look at the search bar

### Expected behavior

The unresponsiveness should be fixed to improve the user experience.

### Desktop (Please provide your system information)

OS: macOS
Browser: Chrome

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

Screenshot 2023-10-18 at 12 10 32 PM

### Relevant log output

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by janvi01**
# Description

Fixed search bar responsiveness in mobile view.

Fixes #1354 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested it locally.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

Screenshot 2023-11-02 at 1 38 19 PM

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by atapas** [comment]
Hi @janvi01 

Thanks for fixing this. Would you be able to fix this issue as well in the filter popup? It is not responsive

image

**Comment by janvi01** [comment]
> Hi @janvi01
> 
> Thanks for fixing this. Would you be able to fix this issue as well in the filter popup? It is not responsive
> 
> image

sure @atapas should I do the changes in the same PR?

**Comment by atapas** [comment]
Yes that works! Thanks a lot :)

**Comment by janvi01** [comment]
@atapas fixed it.

Screenshot 2023-12-18 at 10 12 24 PM

**Review by priyankarpal — APPROVED** [review]

**Comment by atapas** [comment]
I see the build is failing

image

**Comment by priyankarpal** [comment]
> I see the build is failing
> 
> image

linting issue 😿

**Comment by priyankarpal** [comment]
let me clear the cache & deploy the site see

**Review by Sachin-chaurasiya — DISMISSED** [review]

**Comment by Sachin-chaurasiya** [comment]
Hello @janvi01 , build is failing, can you please take a look? Thanks.

**Comment by priyankarpal** [comment]
the error 
Screenshot_2024-01-16_08_06_44

**Review by joshi-kaushal — APPROVED** [review]

**Review by priyankarpal — APPROVED** [review]

**Comment by priyankarpal** [comment]
@all-contributors please add @creater

**Comment by priyankarpal** [comment]
@all-contributors please add @janvi01

**Comment by priyankarpal** [comment]
@all-contributors please add @janvi01 for code

**Comment by priyankarpal** [comment]
@all-contributors please add @janvi01 for code

**Pull request merged**
