### PR TITLE
Remove border bottom and some duplicates line.

### PR DESCRIPTION
**Pull request by rahulpandey70**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Remove border bottom, which cause ```(On clicking or hovering on username)``` layout shifts and also remove two line which is repeated in ```(file name => PlayHeaderActions)```.

Fixes # (issue)
#981 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
@shrilakshmishastry can you please help reviewing this one?

**Comment by shrilakshmishastry** [comment]
hey , this is not the expected behavior, you have completely removed the hovering effect which doesn't handle accessibility expectations. What expected is to have text-border transparent or white color and upon hovering change the color

**Comment by rahulpandey70** [comment]
Hey @atapas @shrilakshmishastry, Made changes according to your suggestions. Please review

**Comment by atapas** [comment]
> Hey @atapas @shrilakshmishastry, Made changes according to your suggestions. Please review

@shrilakshmishastry Can you please review this one if all OK?

**Comment by shrilakshmishastry** [comment]
> > Hey @atapas @shrilakshmishastry, Made changes according to your suggestions. Please review
> 
> @shrilakshmishastry Can you please review this one if all OK?

Hey @atapas how to view UI? vercel link is not available

**Review by koustov — APPROVED** [review]
lgtm

**Pull request closed without merging**
