### PR TITLE
fix(plays): remove redundant css to fix bug#1420

### LINKED ISSUE #1420: 🐛 [Bug report]: The Dynamic Banner's title is not properly aligned
### Descrcibe the bug?

The Dynamic Banner's title is not left aligned. Currently, it is right-aligned, and due to this, it seems too wired.

### Steps to reproduce the bug?

1. Go to **ReactPlay Site**
2. Click on the **Browse Play** button
3. Then, you can see that, **Dynamic Banner's Title** will not be `left-aligned`

### Expected behavior

The title of the plays must be `left-aligned` so it will look better currently it seems that something is broken.

### Desktop (Please provide your system information)

- OS: Windows
- Browser: Chrome, Edge

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

image
Screenshot (1432)
Screenshot (1433)
Screenshot (1434)
Screenshot (1435)

### Relevant log output

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rookieCoder9**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

A css property in a play was causing the h1 to be centre aligned which cause Dynamic Banner Title to be centre aligned.

Fixes #1420 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I attached the image below.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

Screenshot 2024-01-14 at 1 56 53 PM

### CODE REVIEW

**Comment by rookieCoder9** [comment]
@priyankarpal  Kindly review the PR.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉 now it's working

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by rookieCoder9** [comment]
Just one suggestion more @priyankarpal  @Sachin-chaurasiya  when you allow contributors to add play ensure that they don't apply styles at basic html elements. I mean they should have a parent container and add classname to it and then apply CSS. 
Since in React, the external CSS are applied all over the app irrespective of directory. This will cause the website CSS to break now and then. Or they can use some sort of SASS or styled components or some UI library like MUI.

**Comment by Sachin-chaurasiya** [comment]
> Just one suggestion more @priyankarpal @Sachin-chaurasiya when you allow contributors to add play ensure that they don't apply styles at basic html elements. I mean they should have a parent container and add classname to it and then apply CSS. Since in React, the external CSS are applied all over the app irrespective of directory. This will cause the website CSS to break now and then. Or they can use some sort of SASS or styled components or some UI library like MUI.

Thank you for bringing this to our attention, @rookieCoder9. We appreciate your feedback and will make sure to address this issue in the future.

**Pull request merged**
