### PR TITLE
[#2PlaysAMonth]: Random Quote Card Generator

### PR DESCRIPTION
**Pull request by PriteshKiri**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by atapas — COMMENTED** [review]
@PriteshKiri Could you please record a stream as well on stackstream and add the video link by editing your play?

**Comment by PriteshKiri** [comment]
> @PriteshKiri Could you please record a stream as well on stackstream and add the video link by editing your play?

Yes, @atapas

Just recorded a stream on stackstream and updated the link on my play's profile. I hope the stream is recorded well. Please let me know if I have to change anything. Sharing the link here as well for quick navigation: 

Link of my Stackstream: https://www.stack-stream.com/v/random-quote-card-generator-2playsamonth-reactplay-io

**Comment by atapas** [comment]
> > @PriteshKiri Could you please record a stream as well on stackstream and add the video link by editing your play?
> 
> Yes, @atapas
> 
> Just recorded a stream on stackstream and updated the link on my play's profile. I hope the stream is recorded well. Please let me know if I have to change anything. Sharing the link here as well for quick navigation:
> 
> Link of my Stackstream: https://www.stack-stream.com/v/random-quote-card-generator-2playsamonth-reactplay-io

Thank You!

The recording looks great.

**Comment by PriteshKiri** [comment]
> > > @PriteshKiri Could you please record a stream as well on stackstream and add the video link by editing your play?
> > 
> > 
> > Yes, @atapas
> > Just recorded a stream on stackstream and updated the link on my play's profile. I hope the stream is recorded well. Please let me know if I have to change anything. Sharing the link here as well for quick navigation:
> > Link of my Stackstream: https://www.stack-stream.com/v/random-quote-card-generator-2playsamonth-reactplay-io
> 
> Thank You!
> 
> The recording looks great.

Awesome!

Looking forward for the merge so that I can share in on my socials :)

**Review by atapas — APPROVED** [review]
@PriteshKiri Great Job!

I loved it as I completed my test on it. We will merge it, and the play will go LIVE in a few minutes.

Please continue to build the second one :)

Also, feel free to talk about your first play contribution to the world as part of the #2PlaysAMonth challenge and while you do so, don't forget to tag ReactPlay and post a hashtag `#2PLaysAMonth`.

Thanks!

**Comment by PriteshKiri** [comment]
> @PriteshKiri Great Job!
> 
> I loved it as I completed my test on it. We will merge it, and the play will go LIVE in a few minutes.
> 
> Please continue to build the second one :)
> 
> Also, feel free to talk about your first play contribution to the world as part of the #2PlaysAMonth challenge and while you do so, don't forget to tag ReactPlay and post a hashtag `#2PLaysAMonth`.
> 
> Thanks!

Thank you so much @atapas !

Will surely share this on my socials once the link goes live 🙌

**Pull request merged**
