### PR TITLE
in Gallery.js a setData was initialized but never used so fixed that …

### PR DESCRIPTION
**Pull request by Deepakbabani**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Made some changes in HackathonBanner.jsx file, in this file there were some unused imports like useState and AiFillGithub so i removed that unused code.
In Gallery.js file there was a state setData which was defined but was never in used so now after that filter function the filtered data can be found in result variable and using setData(result) it will reflect on the screen also.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by atapas** [comment]
@Deepakbabani What's the issue.. Please update the title and description properly to start review.

**Comment by koustov** [comment]
> @Deepakbabani What's the issue.. Please update the title and description properly to start review.

@Deepakbabani ?

**Comment by Deepakbabani** [comment]
> > @Deepakbabani What's the issue.. Please update the title and description properly to start review.
> 
> @Deepakbabani ?

Some warnings were there so i just removed some unused imports in those files.

**Comment by atapas** [comment]
Hi @Deepakbabani Please take care of it.

**Pull request closed without merging**
