### PR TITLE
lazy load contributor images

### PR DESCRIPTION
**Pull request by abhi-works**
lazy load contributor images

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by abhi-works** [comment]
https://github.com/reactplay/react-play/issues/639 linked to this issue @atapas

**Comment by Angryman18** [comment]
@atapas deploy

**Comment by abhi-works** [comment]
Extended. this feature to lazy load  thumbnail cover images and user avatars

**Comment by Angryman18** [comment]
deploy it

**Review by koustov — APPROVED** [review]
lgtm

**Review by Angryman18 — APPROVED** [review]

**Review by atapas — APPROVED** [review]
Accepted

**Comment by atapas** [comment]
@all-contributors please add @abhi-works for Code

**Pull request merged**
