### PR TITLE
Added Back Button in Pokemon-Stats

### PR DESCRIPTION
**Pull request by GodStarLord**
## Description
After the user searches for a Pokemon, to search for another pokemon, the user needs to reload the pokemon-stats causing bad user experience. Added back button which takes the user to the initial search UI

## Type of change

:heavy_check_mark:: **Enhancement**

### CODE REVIEW

**Comment by atapas** [comment]
@GodStarLord Where is the issue? Please add the issue and link it to the PR for the review to start.

**Comment by GodStarLord** [comment]
Hi @atapas, I have created the issue #689 for this pull request.

**Comment by GodStarLord** [comment]
**Issue #689** - Need to reload the play
msedge_mTSA9qn04H

**Resolution provided in this pull request** #646 
Added back button, no need to reload the play
msedge_iAtVdgvhFB

**Comment by GodStarLord** [comment]
resolved the conflicts due to file changes in the Pokemon-stats play from .jsx to .tsx

**Review by koustov — APPROVED** [review]
lgtm

**Comment by GodStarLord** [comment]
@atapas  can you please do the code review?

**Review by atapas — APPROVED** [review]
Looks good.

**Pull request merged**
