### PR TITLE
Added Cypress test for home page

### LINKED ISSUE #503: ✨ [Feature request]: Add E2E test for react-play
Add basic test for home page with cypress which is described in the wiki
https://github.com/reactplay/react-play/wiki/End-to-End-Test-Scenarios#home-page

Home Page

- [x] The Contributors List should be rendered
- [x] The Twitter Community tweet section must be rendered.
- [x] The Browse button must be present
- [x] The GitHub button must be present
- [x] The Header elements must be present

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
I have added basic test case for home page

Fixes #503

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Locally tested
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ShaileshParmar11** [comment]
PR is ready for review

**Comment by koustov** [comment]
Deployment error
image

@ShaileshParmar11 can you check

**Comment by ShaileshParmar11** [comment]
> Deployment error image
> 
> @ShaileshParmar11 can you check

I dont think it is something related to cypress can you retry deploying?

**Comment by atapas** [comment]
@ShaileshParmar11 The buils issue is successful. The test continues to fail though

**Comment by ShaileshParmar11** [comment]
It is running test from main branch, once this pr is merged it will be resolved

**Review by atapas — APPROVED** [review]

**Pull request merged**
