### PR TITLE
Dark and Light Mode Implemented on the ReactPlay Website

### LINKED ISSUE #424: ✨ [Feature request]:  Dark mode/Light on react play
Hi ReactPlay Team ,As a developers I would love to see ReactPlay in dark mode too hoping it will be released soon.

### PR DESCRIPTION
**Pull request by EOEboh**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

A **dark** and **Light** mode implemented on the website, the toggle button can be found at a strategic place at the navbar just beside the ReactPlay logo.

All the user needs to do is toggle the button to switch to the preferred mode.

The `react-switch` library was used for the toggle component.

Fixes #424 

## Feature

Please delete options that are not relevant.

- [ x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Yes, it has been tested on Chrome and Safari browsers respectively.

It has been tested across all major screen sizes and viewports.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by koustov — CHANGES_REQUESTED** [review]
Hello @EOEboh  I feel the dark theme is not well optimized with the current design language. Also the switch a way off than standard practice

As a traditional way of working on the aesthetic/style/structure changes, I would suggest preparing a mock and reviewing it with the community before incorporation. You can do it over discord. If the action has already been performed, just point me to the appropriate mopckup.

**Comment by EOEboh** [comment]
> Hello @EOEboh I feel the dark theme is not well optimized with the current design language. Also the switch a way off than standard practice. And its not persisting
> 
> As a traditional way of working on the aesthetic/style/structure changes, I would suggest preparing a mock and reviewing it with the community before incorporation. You can do it over discord. If the action has already been performed, just point me to the appropriate mopckup.

Hey Koustov, so please what are you saying in summary.

I can't quite understand what you mean sir

**Comment by ammaaraslam** [comment]
Hi @EOEboh, just as @koustov mentioned, the implementation can be a bit more optimized. And also, instead of a toggle, I think that an icon button _(like the ideas button)_ to the right of the navbar is more suitable. The toggle just seems a bit odd, that's just my opinion, let's see what others think about it too.

**Comment by ammaaraslam** [comment]
Hi @EOEboh, just as @koustov mentioned, the implementation can be a bit more optimized. 
And also, instead of a toggle, I think that an icon button (like the ideas button) to the right of the navbar is more suitable. The toggle just seems a bit odd, that's just my opinion, let's see what others think about it too.

**Comment by ammaaraslam** [comment]
> > Hello @EOEboh I feel the dark theme is not well optimized with the current design language. Also the switch a way off than standard practice. And its not persisting
> > As a traditional way of working on the aesthetic/style/structure changes, I would suggest preparing a mock and reviewing it with the community before incorporation. You can do it over discord. If the action has already been performed, just point me to the appropriate mopckup.
> 
> Hey Koustov, so please what are you saying in summary.
> 
> I can't quite understand what you mean sir

I think what @koustov is trying to convey is that, try to follow the code structure and best practices of ReactPlay. _(like use of variables, functions, commenting, etc.)_.

Also that before coding out the feature, first design a mockup maybe in Figma or any other software you prefer and then share it with the community and ask for feedback. In that way, if there's any change, you can do it in the mockup and can implement the final mockup with code. If you have any doubts please let us know.

**Comment by koustov** [comment]
Hello @EOEboh , let me put the items in a bulleted way in this comments for better understanding
1. When we implement any theme we need to see every element goes well together with it from a `contrast` perspective. What I felt is, the dark theme here is not adjusted fro that front
e.g.: 
image
image

2. The `switch` here sits at a very odd place, without any specific visual indicator to represent what the switch does
3. The `tech-stack` page is not honoring theme selection. Its always dark
image

4. The play list page also having the same issue
image

5. The expectation would be, that when I switch a theme it should persist for me. Like if I refresh, it should retain my selection. This is not happening
6. `The Most Important` item: When we make any major adjustment to UI, process-wise we should create a mockup first . The get this mockup reviewed with the community. Once its approved then we go for implementation/merge. We have done similar process in past (for example we did mock review for Twitter mention implementation)

**Comment by ammaaraslam** [comment]
@EOEboh, I think @koustov has put everything that's needed in an understandable way. Do consider those points when implementing it. So if you need any help in creating this functionality, do let us know.

**Comment by frankiefab100** [comment]
Is this issue still open?
Is there an existing react play design, so I can easily implement the dark mode features.

**Comment by atapas** [comment]
It's not in plan for now.

**Comment by frankiefab100** [comment]
> It's not in plan for now.

Alright

**Pull request closed without merging**
