### PR TITLE
Update Create Issue template format 

### PR DESCRIPTION
**Pull request by muzaffar640**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

The issue template has been updated in yml way. There are few benefits to it

1. It looks better 😊
2. It is like filling out a form now.
3. It will be helpful for non-code contributors to create an issue.
4. We can make some mandatory fields, so contributors can't skip those fields.

Fixes # [issue](https://github.com/reactplay/react-play/issues/652)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have opened the yml page on GitHub and checked the possible output.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Additional context
Please confirm the `Required` and `Non Required` input fields of these issue forms. I have followed my assumption. I will update accordingly.

# Screenshot
**Just think a `Submit New Issue` button at bottom right**
**New Play Template** 👇
Screenshot 2022-10-09 at 1 14 09 PM

**Bug Report Template** 👇
Screenshot 2022-10-09 at 1 14 39 PM
Screenshot 2022-10-09 at 1 14 55 PM

**Feature Request Template** 👇
Screenshot 2022-10-09 at 1 13 36 PM
Screenshot 2022-10-09 at 1 13 55 PM

### CODE REVIEW

**Comment by muzaffar640** [comment]
Review Ready

**Review by atapas — COMMENTED** [review]
@muzaffar640 

Can I please get screen shot of how they will look like?

**Comment by muzaffar640** [comment]
> @muzaffar640
> 
> Can I please get screen shot of how they will look like?

I have already attached it to the PR. It is a little confusing I can understand. there is a total of five screenshots. Let make add more context to PR.

**Review by atapas — APPROVED** [review]
@muzaffar640 Looks Good.

**Pull request merged**
