### PR TITLE
404 Page redirect to home page issue Resolved

### LINKED ISSUE #855: 🐛 [Bug report]:  404 Page should redirect to home page
### Descrcibe the bug?

There are two issues
1. Currently 404 page says `Why don't you go back to home.. Redirecting in X sec.`. This is misleading as automatic redirection takes to `/plays` instead of home page
2. The text `home` should be hyperlinked with home page

### Steps to reproduce the bug?

1. Go to `reactplay.io`
2. Manullu update the url to something that doesn't exist in route table

### Expected behavior

As described in description

### Desktop (Please provide your system information)

Any

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Abhishek-90**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #855 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by Abhishek-90** [comment]
@atapas  @koustov please review the changes.

**Comment by atapas** [comment]
@koustov can you plz review?

**Review by koustov — APPROVED** [review]
lgtm

**Review by Sachin-chaurasiya — APPROVED** [review]
Great work @Abhishek-90  🙌🏻,
Thanks for the contributions ✨

**Pull request merged**
