### PR TITLE
fix:dynamic port set on localhost

### LINKED ISSUE #1243: ✨ [Feature request]:  Set the PORT number dynamically on local server.
### Is your feature request related to a problem? Please describe.

When we try to create a new play on localhost and If we already have something running on port 3000 then the project successfully runs on a different port but when we hit the create play button it redirects to port 3000 which is not the intended port for the project.

### Describe the solution you'd like.

The current solution wants us to set the port number in a .env file If we do that it will successfully open the new play form on that port but what I am suggesting is that we exclude the need to set an env variable for this specific purpose.

### Describe alternatives you've considered.

none

### Screenshot / Screenshare

inside CreatePaly file 
image
This is the code that needs to be updated/

### Additional context

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Hat52**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

When running the project locally and hitting the create play button if you are running the a port other than 3000 the redirection was not working properly, this PR fixes that issue by dynamically set the port to redirect to.

Fixes #1243 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally

# Checklist:

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by joshi-kaushal** [comment]
Can you please test this branch locally, @priyankarpal?

**Comment by priyankarpal** [comment]
@Hat52 could you attack a video? not running in my local system

**Comment by Hat52** [comment]
> @Hat52 could you attach a video? not running in my local system  

sure will do that

**Comment by priyankarpal** [comment]
any updates? @Hat52

**Pull request closed without merging**
