### PR TITLE
Fix/1408 tip calculator design

### PR DESCRIPTION
**Pull request by ehasanrobin**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by ehasanrobin** [comment]
design issue fixed and also state is updating

**Review by priyankarpal — CHANGES_REQUESTED** [review]
there are some errors, please check 
image

**Comment by priyankarpal** [comment]
Could you please add the issue number, even though it has already been assigned to someone?

**Comment by priyankarpal** [comment]
there no updates for 2 weeks so we have to close the PR

**Pull request closed without merging**
