### PR TITLE
React translator #hackoctober

### LINKED ISSUE #1329: [Add a Play]:  React Language translator
### What's the Play about?

The play is a simple react based application which translate any language to any other language 
A user will select in what language they want to write then user will select in what language he/she wants the result

translaotr

### What ReactJS concept will be used to create this play?

Simple use of react hooks like useState was used to manage state changes and fucntion for API call

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by irfanmit**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Hi, i have added a new play that is **react translator** application which translates any written language to any other language

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

No issues was fixed
This is for hackoctober fest 
No extra dependencies was used while making this app

Fixes #1329

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
I have tested the application on my local machine it works well and it has no issues 
**Play is completely bug free**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
translaotr

### CODE REVIEW

**Comment by irfanmit** [comment]
**Issue no - #1329**

**Comment by priyankarpal** [comment]
@irfanmit in future please avoid creating PR without being assigned.

**Comment by irfanmit** [comment]
> @irfanmit in future please avoid creating PR without being assigned.

I apologize for this...should i close this **PR** and **re-open** when assigned on issue #1329?

**Comment by priyankarpal** [comment]
> > @irfanmit in future please avoid creating PR without being assigned.
> 
> I apologize for this...should i close this **PR** and **re-open** when assigned on issue #1329?

no no

**Review by priyankarpal — CHANGES_REQUESTED** [review]
hello @irfanmit please check the code there is a stopwatch project code

**Comment by irfanmit** [comment]
> hello @irfanmit please check the code there is a stopwatch project code

well....sorry but i did not get you
this is a different application
i have two PR one is **#1278**(Stopwatch) and **#1330** (Translator)

**THIS IS A TRANSLATOR APP CODE**
translaotr

**THIS IS STOPWATCH APP CODE**
stopwatch

am i doing anything wrong here? can you specify sir please

**Comment by Sachin-chaurasiya** [comment]
Hi @irfanmit, thanks for your contribution. Please only include files related to the translator play in this pull request. It seems there are changes for other plays as well. Can you remove those and keep only the translator play changes?

**Pull request closed without merging**
