### PR TITLE
Add new play (dev-dash)

### PR DESCRIPTION
**Pull request by shreyazz**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

#394 I tried to add a new play, but it wasn't visible on the localhost. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

new play

# How Has This Been Tested?

Tested on localhost

# Checklist:

- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
Hi @shreyazz How is it going with the play? We have the new flow in for creating play, if you want you can try that too.

**Comment by atapas** [comment]
@shreyazz are you building it anymore?

**Comment by koustov** [comment]
@shreyazz could you please resolve the conflict

**Comment by atapas** [comment]
Hello @shreyazz 

A reminder to get back on this play. This PR may be closed due to a lack of activities soon. Please let us know if you need any help.

Looking forward to getting the play in!

**Comment by shreyazz** [comment]
Hey,
I am busy with some functions that's why I am not able to work on the play.


Thank you,
Shreyas Pahune

**Comment by atapas** [comment]
Hi @shreyazz 

Are you planning to work on it as part of the hacktoberfest?

**Comment by atapas** [comment]
Closing this PR as No Response for close to a couple of months. Please request to open if still working on it.

**Pull request closed without merging**
