### PR TITLE
Fix padding top of created play page

### PR DESCRIPTION
**Pull request by muzaffar640**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Adjusted `paddingTop` for "Play Created" text. 

Fixes # [626](https://github.com/reactplay/react-play/issues/626)

# Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Checked the layout locally on `play/created/id` route.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshot 
Screenshot 2022-10-11 at 10 42 31 PM

### CODE REVIEW

**Comment by Angryman18** [comment]
why there is a whole lot of css replacements which doesnt satisfies the title `Fix padding top of created play page`

**Comment by koustov** [comment]
> why there is a whole lot of css replacements which doesnt satisfies the title `Fix padding top of created play page`

This might be because of different prettier configurations. Please check once with the `Hide Whitespace` filter.

**Comment by Angryman18** [comment]
> > why there is a whole lot of css replacements which doesnt satisfies the title `Fix padding top of created play page`
> 
> This might be because of different prettier configurations. Please check once with the `Hide Whitespace` filter.

yes i just see it.

**Review by koustov — APPROVED** [review]
lgtm

**Review by atapas — APPROVED** [review]

**Pull request merged**
