### PR TITLE
bugfix: When activities on, the mobile view is missing the Events text

### LINKED ISSUE #1227: 🐛 [Bug report]: When activities on, the mobile view is missing the "Events" text
### Descrcibe the bug?

When activity is on, the reactplay web site misses the"Events" text on the mobile. 

Expected the"Event" button should be available to see. The link is working and the icon is there but the text is missing or white color. Possibly

### Steps to reproduce the bug?

1. Launch reactplay.io on mobile view
2. Open the burger button/menu on mobile
3. Look out for the Events button on top

### Expected behavior

We should see the Button name/ the text "Events"

### Desktop (Please provide your system information)

Devices: Mac Os- ventura 13,
Browsers:  Chrome, Safari, 

### Mobile (Please provide your device information)

 iPhone 11,
 Browsers:  Chrome, Safari, 

### Screenshot / Screenshare

reactplay bug

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by satishchakma**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

bugfix: When activities on, the mobile view is missing the Events text. Now the "Events" text is being shown on mobile menu and also on desktop version.

Fixes #1227

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

reactplay bugfix

### CODE REVIEW

**Comment by atapas** [comment]
@satishchakma Resolve the conflicts

**Comment by satishchakma** [comment]
Hi @atapas I have resolved the conflicts, I think. The error is gone. Would you kindly have a look? Thank you.

**Review by priyankarpal — COMMENTED** [review]
hello @satishchakma I'm not getting any issue you can see here. Can you please provide clarification on how the issue was resolved without modifying the code?

https://github.com/reactplay/react-play/assets/88102392/428b7ac8-c478-4888-82df-4081dc466b19

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue? @satishchakma

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this PR.

**Pull request closed without merging**
