### PR TITLE
Fixes loading text issue

### LINKED ISSUE #1064: 🐛 [Bug report]: there is a "loading..." string that gets visible sometimes
### Descrcibe the bug?

On the reactplay.io/plays page, there is a "loading..." string that gets visible sometimes after navigating between reactplay.io/ and reactplay.io/plays pages a few times.

### Steps to reproduce the bug?

1. Go to reactplay.io
2. Navigate a few times between the root and /plays page
3. Note the "loading..." under the header

### Expected behavior

The "loading..." string should not be shown and the top banner should have been visible

### Desktop (Please provide your system information)

OS: Windows 11
Browser: Chrome 
Version: 111.0.5563.64

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

Recording 2023-03-21 075328

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by CodeVibranium**
Fixes #1064 

# Description
> Issue: loading..." string that gets visible sometimes

- There was an issue with the `setLoading` state in the `DynamicBanner.jsx `component where it was not being set to `false` if the `coverImage` was not found. However, upon further investigation, i found that there is no need for the `loading` state in the `DynamicBanner.jsx` component. This is because the component receives a prop called `randomPlay` from its parent component `PlayList.jsx`, which contains the necessary data to load the coverImage.

-  In the parent component, a `<Loader/>` component is shown until the data has arrived. This loader is shared between both child components. Once the data has arrived, the state (`randomPlay`) is updated, and the `DynamicBanner randomPlay={randomPlay}/>` component is rendered.

- If the image (cover) is not present, we import the image (`randomPlay.slug`) from the `fs`. If there is a concern that this may take some delay, we can add a `<Loader/>` component instead of `<p>loading...</p>`. However, i believe that this is not necessary because the image is bound to exist, and importing a single image should be swift and may not require a `<Loader/>`. However, if it is necessary, we must also have a `<Loader/>` for each `<PlayThumbnail/>` component.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I have tested this in my local machine and it has fixed the required issue.

# Checklist:

- [x] I have performed a self-review of my own code

# Screenshots or example output
> Original size 20 mb, compressed using cildeo now 2mb.
https://user-images.githubusercontent.com/62259994/235495784-b435916c-2a98-4796-a62a-a9fddd10450a.mp4

### CODE REVIEW

**Comment by lalithpk** [comment]
Hello! I would like to contribute to this issue. Could you please confirm if this issue is still ongoing?

**Review by mahabub-bd — COMMENTED** [review]
OK

**Comment by CodeVibranium** [comment]
> OK

Hey @mahabub-bd ,
Any update on my PR?

**Comment by atapas** [comment]
> > OK
> 
> 
> 
> Hey @mahabub-bd ,
> 
> Any update on my PR?

Yes will check soon

**Comment by CodeVibranium** [comment]
> > > OK
> > 
> > 
> > Hey @mahabub-bd ,
> > Any update on my PR?
> 
> Yes will check soon
Hey @atapas,
Any update ?

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
Looks Good to me.

**Pull request merged**
