### PR TITLE
✨ [Feature]: Copy to Clipboard Feature in Wordle Play

### LINKED ISSUE #1358: ✨ [Feature request]: Copy to Clipboard Feature in Wordle Play
### Is your feature request related to a problem? Please describe.

Imagine you're playing your favorite word puzzle, [Wordle Unlimited](https://reactplay.io/plays/samirmishra27/wordle) on React-play's site. And you're stuck figuring out what could this 5-letter word be in this puzzle. 🤔

It would be great if you can share the wordle puzzle with your friends on social media platforms like Discord. Without being bothered to take a screenshot and then cropping it! 🙌

## Share button - Share your wordle puzzle
Share your current puzzle with your friends seamlessly using the share button! The button, located at the top-right of the play's screen will allow you to share an image of the current puzzle by taking a snapshot of the puzzle dom. (Using html2canvas library)

### Describe alternatives you've considered.

Right now there are no alternatives to this approach beside taking a screenshot. (Which may not be of great quality always)

## Demo of share feature on my pilot project!

https://github.com/reactplay/react-play/assets/68955143/425e649d-94c2-40b0-87b1-39592431b3a6

### Additional context

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SamirMishra27**
# Description

Share your current puzzle with your friends seamlessly using the share button! The button, located at the top-right of the play's screen will allow you to share an image of the current puzzle by taking a snapshot of the puzzle dom. (Using html2canvas library)

As described in Issue #1358 This PR adds this feature into the Wordle Play! 🙌

Fixes #1358

Commit Description:
> This commit adds a useful feature to the Wordle play game i.e, share
your tiles with your friends!
>
> The button, located at the top-right of the play's screen will allow you to
share an image of the current puzzle by taking a snapshot of the puzzle dom.
(Using html2canvas library)
>
> Other code changes:
> - Add a share.svg for the button
> - Add styles for the copy to clipboard modal
> - Add a utility function to sleep
> - Change errorSlideRef name to notifSlideRef to be more consistent with
  its usage.
> - Remove animations of wordle tiles after some time using useEffect.
> - Use html2canvas for image generation.
>
> This will successfully close the issue https://github.com/reactplay/react-play/issues/1358.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# Screenshots or example output

To be uploaded...

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@SamirMishra27 please look into it. Not working 

https://github.com/reactplay/react-play/assets/88102392/91d75926-42bf-4596-946f-93c39d61312f

**Comment by SamirMishra27** [comment]
@priyankarpal does it show anything on console ? Also copying takes 1-2 seconds, try again??

**Comment by SamirMishra27** [comment]
> @SamirMishra27 please look into it. Not working
> 
>  2023-10-29_15-14-22.mp4

@priyankarpal Thanks for sharing the issue.

In Brave browser, please make sure you have the 'Shields down' for the site.
image

Please allow this site to copy images/text to your clipboard.
image

### The Problem:
In Brave browser, the `html2canvas` library is taking weirdly longer than usual to convert elements to a canvas. I'm not sure why is this happening. But like I said, it will take a bit of time before copying the tiles to your clipboard.
Please make sure you do the following
- Once you click on "Copy to clipboard", wait until the process is finished and don't un-focus the tab or move anywhere. It will take anywhere between 2-10 seconds to copy it.


https://github.com/reactplay/react-play/assets/68955143/d0f19a28-ea43-4976-85b9-0185f7578a4c
Then it will work as expected.


### Solution: 
I realize the UI for copying the tiles is poorly designed by me, I will be making a follow up commit to add a loading spinner & disable the buttons while copying is in process. In case the procedure fails it will show up an error.

**Comment by priyankarpal** [comment]
got it

**Review by priyankarpal — APPROVED** [review]

**Comment by SamirMishra27** [comment]
@atapas need your approval 🚀

**Pull request merged**
