### PR TITLE
Fix: heading level hierarchy

### LINKED ISSUE #580: 🐛 [Bug report]: Heading levels are not heirarchical
**Describe the bug**
Heading levels are not being used heirarchically which is an accessibility problem.

**To Reproduce**

**Expected behavior**
H1 should be followed by h2, then h3 and so on.

**Screenshots**

**Desktop (please complete the following information):**
 All browsers

**Smartphone (please complete the following information):**
All devices

**Additional context**
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by EmmaDawsonDev**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

The headings were not following the correct hierarchy on all pages. In some places there was no h1, in other places it jumped over levels. 

Fixes #580 

## Type of change

Headings are now semantically correct on all pages. Styling remained the same due to good use of classes for styling.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Visual. Axe Dev Tools

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@koustov Please review this one. Also need to test the changes as some hierarchy changes may disturb CSS(speculating).

**Review by koustov — CHANGES_REQUESTED** [review]
It looks good to me. I just have one ask. Could you please take a screen shot of the `Create Play` page from the dev environment and paste it into this PR. I want to have a closure look at that page once before approving.

**Comment by EmmaDawsonDev** [comment]
Sure, this one? 
image

**Review by koustov — DISMISSED** [review]
lgtm

**Comment by atapas** [comment]
> lgtm

@koustov It says LGTM but not approved. Any reason?

**Comment by atapas** [comment]
@EmmaDawsonDev Time to resolve the conflict of this one.

**Comment by EmmaDawsonDev** [comment]
All fixed :)

**Comment by EmmaDawsonDev** [comment]
Anything else that needs doing?

**Review by atapas — APPROVED** [review]
LGTM

**Comment by atapas** [comment]
@koustov Please approve and merge it.

**Comment by koustov** [comment]
> @koustov Please approve and merge it.

Will finish by EOD today

**Review by koustov — APPROVED** [review]
lgtm

**Pull request merged**
