### PR TITLE
Adding Quote generator

### LINKED ISSUE #829: [Add a Play]: Quote Generator
### What's the Play about?

This is react play which is all about implementing random quote when user will click then random quote will generate with addition feature.

Feature Include like User click on volume sound to listen and can copy the quote using clipboard icon can post the quote on LinkedIn

Refer to this image

Screenshot (53)

### What ReactJS concept will be used to create this play?

Hook, Data Fetching, Window navigation, Tailwind config

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #829 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# Screenshots or example output

Screenshot (53)

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
Do not commit the package-lock json file.

**Review by atapas — CHANGES_REQUESTED** [review]
@Kumar-Ankit56 This play does not follow the workflow to create a flow. I will suggest you check the create-play.md file which explains how can you create a play.

You need to execute a couple of simple commands to get things started. You no need to get in the entire boilerplate code created by CRA or Vite.

Please join our Discord if you need any interactive help. Otherwise, we can comment here as well.

**Comment by Kumar-Ankit56** [comment]
> @Kumar-Ankit56 This play does not follow the workflow to create a flow. I will suggest you check the create-play.md file which explains how can you create a play.
> 
> You need to execute a couple of simple commands to get things started. You no need to get in the entire boilerplate code created by CRA or Vite.
> 
> Please join our Discord if you need any interactive help. Otherwise, we can comment here as well.

Ok sir let me.

**Comment by atapas** [comment]
@Kumar-Ankit56 Any update?

**Comment by Kumar-Ankit56** [comment]
> @Kumar-Ankit56 Any update?
By today only I'm recreating the new fresh Prs

**Pull request closed without merging**
