### PR TITLE
Added Simple Seo Component Play

### PR DESCRIPTION
**Pull request by debjit**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code

# Screenshots or example output
ReactPlay-Simple-Article-SEO-Component (1)

### CODE REVIEW

**Comment by atapas** [comment]
@debjit Is it ready to review?

**Comment by atapas** [comment]
@debjit Can we have a way for people to copy that code section on a click?

**Comment by debjit** [comment]
Yes it is ready for review.

> Can we have a way for people to copy that code section on a click?

Yes! But I think we have to create a component or add a plugins link "react copy to clipboard". I never implement one.

**Comment by atapas** [comment]
> Yes it is ready for review.
> 
> > Can we have a way for people to copy that code section on a click?
> 
> Yes! But I think we have to create a component or add a plugins link "react copy to clipboard". I never implement one.

Thanks! Yeah we can take it as a future enhancement in another ticket.

Btw, the build fails due to linting errors. You need to pull the latest from the upstream main and then follow a few steps for formatting and pointing mentioned in readme. Please get it ready.

**Comment by atapas** [comment]
Hi @debjit 

Can you please fix the linting issues so that we can merge the work?

image

**Comment by debjit** [comment]
Formatted and lint command updated.

**Review by atapas — APPROVED** [review]

**Pull request merged**
