### PR TITLE
Add New Idea: Landing Page

### LINKED ISSUE #283: ✨ [Feature request]: Add New Idea, Landing Page
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to add new idea 💡 for the plays.
This idea is Landing Page.

**Describe alternatives you've considered**

**Additional context**
I am happy to work on

### PR DESCRIPTION
**Pull request by MOHAMED-EHAB-DEV**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Add New Idea: Landing Page using React

Fixes #283 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vasantisuthar** [comment]
Please link the issue generated for this PR.

**Comment by atapas** [comment]
@Programming-School-Pro-Coding Is this PR still valid? Which issue is it connected to?

**Comment by atapas** [comment]
> @Programming-School-Pro-Coding Is this PR still valid? Which issue is it connected to?

@Programming-School-Pro-Coding is this PR needed? Which issue is related to?

**Comment by Sachin-chaurasiya** [comment]
@Programming-School-Pro-Coding , Please add some description and mention the issue number in the PR template.

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding , Please add some description and mention the issue number in the PR template.

#283

**Comment by Programming-School-Pro-Coding** [comment]
> > > @Programming-School-Pro-Coding , Please add some description and mention the issue number in the PR template.
> > 
> > 
> > #283
> 
> @Programming-School-Pro-Coding , You can watch this recording on how to link issues to pull requests.
> 
>  Untitled.3.mp4

Ok, Thank you so so much

**Comment by Programming-School-Pro-Coding** [comment]
> > > @Programming-School-Pro-Coding , Please add some description and mention the issue number in the PR template.
> > 
> > 
> > #283
> 
> @Programming-School-Pro-Coding , You can watch this recording on how to link issues to pull requests.
> 
>  Untitled.3.mp4

Updated with the description

**Comment by Programming-School-Pro-Coding** [comment]
@atapas Please Review

**Comment by atapas** [comment]
Resolve conflict and pull from main

**Comment by Programming-School-Pro-Coding** [comment]
Ok

**Review by koustov — APPROVED** [review]
LGTM however resolve the conflict

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
@Programming-School-Pro-Coding Resolve conflicts to merge

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding Resolve conflicts to merge

Ok

**Comment by atapas** [comment]
> > @Programming-School-Pro-Coding Resolve conflicts to merge
> 
> Ok

@Programming-School-Pro-Coding Please resolve the conflict to merge.

**Comment by atapas** [comment]
@Programming-School-Pro-Coding Following up again. Are you still working on it?

**Pull request closed without merging**
