### PR TITLE
fix #643: div tag present as descendant of p tag

### LINKED ISSUE #643: 🐛 [Bug report]: div tag cannot appear as a descendant of p tag
**Describe the bug**
div tag cannot appear as a descendant of p tag
p tag can only contain inline elements and div tag is a block element.
Putting a div tag inside it is improper.

**To Reproduce**
Steps to reproduce the behaviour:
1. in local development env
2. can see warnings in console.

**Expected behaviour**
Parent elements should be div and inside we can have p tag for texts in ExtendedFooter.

**Screenshots**
Screenshot 2022-10-08 at 10 12 08 AM
Screenshot 2022-10-08 at 10 12 22 AM

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [22]

**Additional context**
Like to work on this. Could you assign me to this?

### PR DESCRIPTION
**Pull request by SSK-14**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

div tag cannot appear as a descendant of p tag
p tag can only contain inline elements and div tag is a block element.
Putting a div tag inside it is improper.

Fixes # (643)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atapas** [comment]
@Angryman18 please review this one.

**Comment by Angryman18** [comment]
deploy it

**Comment by koustov** [comment]
> deploy it

deployment approved

**Review by koustov — APPROVED** [review]
lgtm

**Review by Angryman18 — APPROVED** [review]

**Review by atapas — APPROVED** [review]
Accepting

**Pull request merged**
