### PR TITLE
Code snippets

### PR DESCRIPTION
**Pull request by senali-d**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (#803)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by senali-d** [comment]
Hi, @atapas 
Fix all the merge conflicts with new codebase

**Comment by atapas** [comment]
> Hi, @atapas Fix all the merge conflicts with new codebase

Can you please do it once more @senali-d as we have linting rules now? Please check the readme for the new steps.

**Comment by senali-d** [comment]
> > Hi, @atapas Fix all the merge conflicts with new codebase
> 
> Can you please do it once more @senali-d as we have linting rules now? Please check the readme for the new steps.

@atapas Fix all the merge conflicts and linting issues.

**Comment by atapas** [comment]
@senali-d The build fails

image

Do you use any env variable that we need to ad in vercel?

**Comment by senali-d** [comment]
> @senali-d The build fails
> 
> image
> 
> Do you use any env variable that we need to ad in vercel?

@atapas No any additional env variable used in the new play. Locally I try to build the project it's work without any issue.

**Review by atapas — COMMENTED** [review]
@senali-d I still see the same error. Did you perform all the formatting and linting changes as mentioned in the Readme?

Btw, have you followed the create-react-play to create the basic play structure?

**Comment by atapas** [comment]
> @senali-d I still see the same error. Did you perform all the formatting and linting changes as mentioned in the Readme?
> 
> Btw, have you followed the create-react-play to create the basic play structure?

@senali-d did you get a chance to see this comment?

**Comment by senali-d** [comment]
> > @senali-d I still see the same error. Did you perform all the formatting and linting changes as mentioned in the Readme?
> > Btw, have you followed the create-react-play to create the basic play structure?
> 
> @senali-d did you get a chance to see this comment?

@atapas I'm created a new PR because it was difficult figure out the issue.
Please ref this PR: https://github.com/reactplay/react-play/pull/890

**Comment by senali-d** [comment]
Create new PR #890

**Pull request closed without merging**
