### PR TITLE
[#2PlaysAmonth] emoji guess game

### LINKED ISSUE #954: [#2PlaysAMonth]: Emoji guess game
### What's the Play about?

The user will be given a list of emoji to select from.The emojis would be split in 3 row the user has to pick from the 3 times , now the game will display the card 

### What ReactJS concept will be used to create this play?

useState, 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rashy10**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #954 

Added the emoji game and its component on the specified branch 

## Type of change
Adding a game 

Motivation 
This was a card game that really fascinated me, the game is simple and uses usestate to implement the game

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

The test was conducted on all the possible outcome or result of the game, ]

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

**Comment by atapas** [comment]
Hi @rashy10 

When you create the PR, there is an option to specify the issue link.

```
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
```

Please edit the description and put it

**Comment by atapas** [comment]
@rashy10 what's the issue number?

**Comment by rashy10** [comment]
> @rashy10 what's the issue number?

Hi sir, the issue number is #954

**Comment by atapas** [comment]
@rashy10 Kindly resolve the merge conflicts

**Comment by atapas** [comment]
Hi @rashy10 Could you please make the PR ready for merge?

image

**Comment by atapas** [comment]
> Hi @rashy10 Could you please make the PR ready for merge?
> 
> image

@rashy10 Reminder

**Comment by rashy10** [comment]
hi sir I have made the changes , can you check again sir

**Comment by atapas** [comment]
@rashy10 you seem to have closed the PR

**Comment by rashy10** [comment]
yes sir i closed it some issue , i couldnt really understand so closed it , now made new PR #1008

**Comment by atapas** [comment]
> yes sir i closed it some issue , i couldnt really understand so closed it , now made new PR #1008

You were very near to completion. You just had to run the linting and formatting commands mention in the readme @rashy10.

IMO, its not great to leave the hard work because you need to understand it. We are available on Discord to help you and make you understand. So feel free to get back at any time. Thanks!

**Comment by rashy10** [comment]
> > yes sir i closed it some issue , i couldnt really understand so closed it , now made new PR #1008
> 
> You were very near to completion. You just had to run the linting, and formatting commands mentioned in the readme @rashy10.
> 
> IMO, it is not great to leave the hard work because you need to understand it further. We are available on Discord to help you and make you understand. So feel free to get back at any time. Thanks!

Yes sir sure,Sir I understood the mistake and corrected it in the new PR #1008 ,the linting and formatting is done sir, I am new to github ,so was trying and exploring to make PR, now figured out how github works ,so tried new PR #1008 , the problem is with cypress run

**Pull request closed without merging**
