### PR TITLE
Add Play Audio-Visualizer

### PR DESCRIPTION
**Pull request by DyingintheDarkness**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
- This the PR for the play "Audio-Visualizer"
- Fixes https://github.com/reactplay/react-play/issues/822

## Type of change
Added new play "Audio-Visualizer"

# How Has This Been Tested?
- I verified my changes through end-to-end testing across all viewports.

# Checklist:
- [x]  I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x]  I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] New Play (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by atapas** [comment]
@DyingintheDarkness Could you please resolve the conflicts?

**Comment by DyingintheDarkness** [comment]
> @DyingintheDarkness Could you please resolve the conflicts?

I will update node-sass to version 8.0.0. p5.js-sound is not compatible with version 1.0.0 and above due to this issue (https://github.com/processing/p5.js-sound/issues/453). So, I will need to use version 0.9.0 of p5.js for it to work....

**Comment by atapas** [comment]
> @DyingintheDarkness Could you please resolve the conflicts?

Any update?

**Comment by DyingintheDarkness** [comment]
> > @DyingintheDarkness Could you please resolve the conflicts?
> 
> Any update?

I have fixed the conflicts. I have ran the tests and all are passing.

**Comment by DyingintheDarkness** [comment]
can you check up on it? any thing i need to change...? i have resolved conflicts @atapas

**Pull request closed without merging**
