### PR TITLE
Issue#1064 loading bug in ui

### PR DESCRIPTION
**Pull request by npiyush97**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
https://github.com/reactplay/react-play/issues/1064

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

# Screenshots or example output

removed unnecessary loading check.

### CODE REVIEW

**Comment by npiyush97** [comment]
!pr review needed 
@atapas @koustov 
I remove loading... with your loader if want to different loading style than existing one let me know

**Comment by npiyush97** [comment]
@Sachin-chaurasiya pr review !

**Comment by koustov** [comment]
@npiyush97 please resolve the conflict

**Comment by koustov** [comment]
This PR is targeting the issue as https://github.com/reactplay/react-play/pull/1075

**Comment by npiyush97** [comment]
Error: Timeout awaiting 'request' for 30000ms

@koustov I think this error does not conflict with my code, poor optimization?

**Pull request closed without merging**
