### PR TITLE
Creation date added to Play header

### LINKED ISSUE #862: ✨ [Feature request]: Show the Play creation date in the play page
### Is your feature request related to a problem? Please describe.

Right now the play page doesn't show when the play was created. Could you show the play creation date?

### Describe the solution you'd like.

The play creation date should be in the header where we show other meta data like who created the paly, photo etc.

The date must be,
- Formatted properly
- Must be locale-aware to the browser.

### Describe alternatives you've considered.

None

### Screenshot / Screenshare

image

### Additional context

We already use the date-fns library. Please utilize that for the formatting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ankitk26**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Creation date for any play was added to the PlayHeader component. The date-fns library was used to get the locale-aware format of the date.

Fixes #862 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Different locale formats were added manually to check the right format of the date.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
image

### CODE REVIEW

**Comment by atapas** [comment]
@ankitk26 The build fails

image

**Comment by ankitk26** [comment]
I will push the changes after fixing the error soon

**Comment by atapas** [comment]
@koustov Can you please review this one?

**Comment by atapas** [comment]
The build still fails

image

Please fix the lint errors and run the yarn build locally.

**Comment by ankitk26** [comment]
Hi @atapas, I ran the yarn build command and it's creating the build folder without any errors.  I fixed the eslint error of alphabetically sorted props and pushed the changes in the previous commit.
image

**Comment by atapas** [comment]
@ankitk26 Finally it got built.

A small comment on it. I see the vertical alignment of the dot, and the date is a bit off. Can you please fix that for merge?

image

**Review by atapas — APPROVED** [review]

**Pull request merged**
