### PR TITLE
added play pathfinding visualizer

### LINKED ISSUE #826: [Add a Play]: Pathfinding Visualizer
### What's the Play about?

Visualizes shortest path finding algorithms like 'Dijkstra' on a grid.

### What ReactJS concept will be used to create this play?

react, react-bootstrap, useEffect

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Ananya2001-an**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Added a new react play called "Shortest Pathfinding Visualizer". This play allows users to choose some end points on a grid and run some pathfinding algorithm like Dijkstra to see how that algorithm is conducting the search process. Implemented nice visual CSS animations to show the entire search process. 

Fixes #826 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

image

### CODE REVIEW

**Comment by atapas** [comment]
@Ananya2001-an Please post a message when it is ready for review.

**Comment by Ananya2001-an** [comment]
Yes kindly review it.

**Comment by Ananya2001-an** [comment]
Hi @atapas sir. Added some changes to the PR. Kindly deploy and review the changes.

**Comment by atapas** [comment]
@Ananya2001-an Great play!

Can you please take care of the responsiveness?

image

**Comment by Ananya2001-an** [comment]
@atapas yeah sure I will work on it

**Comment by Ananya2001-an** [comment]
@atapas I am not able to install dependencies like bootstrap, react- bootstrap...can you guide?

**Comment by atapas** [comment]
> @atapas I am not able to install dependencies like bootstrap, react- bootstrap...can you guide?

What's the error?

And why do you need it?

**Comment by Ananya2001-an** [comment]
> > @atapas I am not able to install dependencies like bootstrap, react- bootstrap...can you guide?
> 
> What's the error?
> 
> And why do you need it?

I just wanted to use some of the react bootstrap components to improve the ui while I am trying to make it responsive.

**Comment by Ananya2001-an** [comment]
@atapas sure I will make some updates today; just got busy with some outside work.

**Comment by Ananya2001-an** [comment]
@atapas added changes in styles.css file to make play responsive, kindly check.

**Comment by atapas** [comment]
Hey @Ananya2001-an Sorry it took time for me to look into it due to my vacation.

In the mean time, we have added a bunch of linting rules. Could you please update your branch from main and perform a `yarn install` and `yarn start`? You may have to fix the linting errors for the build to get successful.

Once done. I shall do the final review.

**Comment by Ananya2001-an** [comment]
@atapas yeah sure

**Comment by atapas** [comment]
> @atapas yeah sure

Any update?

**Comment by Ananya2001-an** [comment]
@atapas Sorry I don't have any updates. I will surely make the requested changes today. I was actually busy with some exams.

**Comment by Ananya2001-an** [comment]
@atapas kindly review the changes.

**Comment by Ananya2001-an** [comment]
Hey @atapas can you review my PR now ?

**Comment by atapas** [comment]
@Ananya2001-an I checked it.

Found a couple of issues in my test.

1. When I do first and last node and click on visualize without changing the algo(as by default one is set), nothing happens.
2. Then if I change it to an algo and click on visualize, it works.
3. Then if I change the algo again and visualize, it goes unresponsive.

You need to check these and fix.

**Comment by Ananya2001-an** [comment]
@atapas actually by default no algorithm is chosen you have to select one and then its name will be shown instead of Algorithms. Besides that the third issue is something I will look into.

**Comment by atapas** [comment]
> @atapas actually by default no algorithm is chosen you have to select one and then its name will be shown instead of Algorithms. Besides that the third issue is something I will look into.

Yes first one is a UX problem, not so much functional. When I land on the play, as the option is shown in the listbox, user will assume that's one selected too. So we need to do either of these:

- Whatever algo we show on landing in the listbox, lets select that by default.
- Do not show any algos when we land, let users exiplicly select one before visualizing.

**Comment by atapas** [comment]
> > @atapas actually by default no algorithm is chosen you have to select one and then its name will be shown instead of Algorithms. Besides that the third issue is something I will look into.
> 
> 
> 
> Yes first one is a UX problem, not so much functional. When I land on the play, as the option is shown in the listbox, user will assume that's one selected too. So we need to do either of these:
> 
> 
> 
> - Whatever algo we show on landing in the listbox, lets select that by default.
> 
> - Do not show any algos when we land, let users exiplicly select one before visualizing. 

@Ananya2001-an are you able to reproduce this one at your end?

**Comment by Ananya2001-an** [comment]
I was able to fix the default algo issue but the second one is still not solved

**Comment by Ananya2001-an** [comment]
Hi @atapas I have kept a default choice for algorithms but the replay thing is not working as if now. I tried many ways but it's getting a bit complex. I will have to refactor it later. Can you merge this for now and I will definitely think of some way in future to fix it somehow.

**Comment by atapas** [comment]
Will get on it, if all taken care.

**Pull request closed without merging**
