### PR TITLE
feat: hover effect on home page elements & redirecting to their respective pages 

### LINKED ISSUE #1262: ✨ [Feature request]: Requesting Animations on the Home Page
### Is your feature request related to a problem? Please describe.

When I am scrolling through the home page, I notice that there are no animations. Therefore, I kindly request the addition of animations to the website's home page.

### Describe the solution you'd like.

By utilizing Framer Motion or any other suitable library, we can create stunning animations that will enhance the visual appeal of the home page

### Describe alternatives you've considered.

For now, I am unable to think of any alternatives to this

### Screenshot / Screenshare

framer

### Additional context

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by letscodedanish**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
This PR adds the missing animation on the website, In the whole website each button have some hover effect but on home page "Learn","Create" and "Socialize" button has no effect on it which looks odd.
I also added the cursor pointer on hover.

Fixes #1262 

## Type of change
Change in UI.

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Tested on my local system.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

Screenshot (507)

### CODE REVIEW

**Comment by letscodedanish** [comment]
@priyankarpal please review it.

**Review by priyankarpal — DISMISSED** [review]
Looks Good 🎉

**Comment by atapas** [comment]
@letscodedanish @priyankarpal 

I liked the changes. However I have some thouhts...

Now Learn Create Share looks like they are links. It gives us an opportunity to actually link them meaningfully.

- Learn can be linked to /plays
- Create can be linked to how the 'Create' button is linked
- Share can be linked to this modal we already have.. 
image


What do you think?

**Comment by priyankarpal** [comment]
> @letscodedanish @priyankarpal
> 
> I liked the changes. However I have some thoughts...
> 
> Now Learn Create Share looks like they are links. It gives us an opportunity to actually link them meaningfully.
> 
> * Learn can be linked to /plays
> * Create can be linked to how the 'Create' button is linked
> * Share can be linked to this modal we already have..
>   image
> 
> What do you think?

yeah! it would be great if we do.

**Comment by atapas** [comment]
> > @letscodedanish @priyankarpal
> > I liked the changes. However I have some thoughts...
> > Now Learn Create Share looks like they are links. It gives us an opportunity to actually link them meaningfully.
> > 
> > * Learn can be linked to /plays
> > * Create can be linked to how the 'Create' button is linked
> > * Share can be linked to this modal we already have..
> >   image
> > 
> > What do you think?
> 
> yeah! it would be great if we do.

@letscodedanish Do you want to take up these changes?

**Comment by letscodedanish** [comment]
Yes @atapas im taking up these changes, i would like to know the path for each button where we will be redirected by clicking on it.

**Comment by atapas** [comment]
> Yes @atapas im taking up these changes, i would like to know the path for each button where we will be redirected by clicking on it. 

Yeah that I mentioned in my earlier comment.

**Comment by letscodedanish** [comment]
@atapas I have done the changes you suggested, its working fine for all the three icons.
Learn is linked to /plays
Create is linked to the 'Create' button
Share is linked to the modal we already have.

**Comment by letscodedanish** [comment]
@atapas please review it, so that i can do the further changes if needed.

**Comment by atapas** [comment]
> https://app.netlify.com/sites/reactplayio/deploys/6527c8492676f90008532962

image

**Review by priyankarpal — CHANGES_REQUESTED** [review]

**Comment by atapas** [comment]
@letscodedanish 

Let me know when errors are fixed. It still fails

image

**Comment by letscodedanish** [comment]
@atapas have a look.

**Comment by atapas** [comment]
> https://app.netlify.com/sites/reactplayio/deploys/6528e6166e1a9a00087d9fd2

Still got one lint error

image

**Comment by atapas** [comment]
@letscodedanish 

still 
image

**Comment by letscodedanish** [comment]
@atapas I dont know why its giving prettier error, i have done the correct spacing according to the linting rules. If you can suggest something?

**Comment by letscodedanish** [comment]
@atapas check on the latest commit, in my system it's not giving an error, if it still gives an error while deploying we can drop the idea of socialize modal pop-up and can simply redirect to the footer part.
For the "Learn" and "Create" button it's working totally fine the animation and the functionality both.

**Comment by atapas** [comment]
@letscodedanish You just need to put an enter(new line on the specified line number)

image

**Comment by letscodedanish** [comment]
> @letscodedanish You just need to put an enter(new line on the specified line number)
> 
> image

okay @atapas I did that , have a look.

**Comment by atapas** [comment]
@letscodedanish Understand the error here:

image

At the line number 21, you have a space then enter.. instead it is asking you to remove the space before the enter.

Btw, doesn't  the lint error comes in dev mode?

**Comment by letscodedanish** [comment]
> @letscodedanish Understand the error here:
> 
> image
> 
> At the line number 21, you have a space then enter.. instead it is asking you to remove the space before the enter.
> 
> Btw, doesn't the lint error comes in dev mode?

I fixed what you said, and yes the lint errors are not coming in dev mode. Everything is working as per we wanted if this errors doesn't count.

**Comment by atapas** [comment]
> > @letscodedanish Understand the error here:
> > image
> > At the line number 21, you have a space then enter.. instead it is asking you to remove the space before the enter.
> > Btw, doesn't the lint error comes in dev mode?
> 
> I fixed what you said, and yes the lint errors are not coming in dev mode. Everything is working as per we wanted if this errors doesn't count.

This is concerning.. because this PR is very close to done... But now able to test out due to lint issues. Could you please confirm you are running all the format and lint commands mentioned in the readme?

You previous link fixed worked but there is one more.

image

**Comment by priyankarpal** [comment]
I just remove the extra space & let see

**Comment by priyankarpal** [comment]
> Can we do it @priyankarpal @atapas as my hacktoberfest timer is going to end.

It still has the same error. format code & lets see 

https://github.com/reactplay/react-play?tab=readme-ov-file#format-the-code

**Comment by letscodedanish** [comment]
Screenshot (535)

**Comment by letscodedanish** [comment]
I have only added the functionality of "Learn" and "Create" for now to avoid the error and see the hover effect, we can take the socialize button in a new PR separately. For now please have a look on it @priyankarpal @atapas .

**Comment by letscodedanish** [comment]
@priyankarpal please have a look on it.

**Pull request closed without merging**
